<ul id="tabul">
    <li class='home' url="<?= URL_BASE.'index/comingsoom?page=home&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left home_left"></div>
            <div class="newmenu_bg home_bg">
                <div style="padding-top:20px;">Home</div>
            </div>
            <div class="newmenu_right home_right"></div>
        </a>
    </li>
    <li class='applications' url="<?= URL_BASE.'index/comingsoom?page=applications&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left applications_left"></div>
            <div class="newmenu_bg applications_bg">
                <div style="padding-top:20px;">Applications</div>
            </div>
            <div class="newmenu_right applications_right"></div>
        </a>
    </li>
    <li class="students" url="<?= URL_BASE.'index/index?page=students&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left students_left_hover"></div>
            <div class="newmenu_bg students_bg_hover">
                <div style="padding-top:20px;">Students</div>
            </div>
            <div class="newmenu_right students_right_hover"></div>
        </a>
    </li>
    <li class="teachers" url="<?= URL_BASE.'index/comingsoom?page=teachers&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left teachers_left"></div>
            <div class="newmenu_bg teachers_bg">
                <div style="padding-top:20px;">Teachers</div>
            </div>
            <div class="newmenu_right teachers_right"></div>
        </a>
    </li>
    <li class="courses" url="<?= URL_BASE.'index/comingsoom?page=courses&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left courses_left"></div>
            <div class="newmenu_bg courses_bg">
                <div style="padding-top:20px;">Courses</div>
            </div>
            <div class="newmenu_right courses_right"></div>
        </a>
    </li>
    <li class="sections" url="<?= URL_BASE.'index/comingsoom?page=sections&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left sections_left"></div>
            <div class="newmenu_bg sections_bg">
                <div style="padding-top:20px;">Sections</div>
            </div>
            <div class="newmenu_right sections_right"></div>
        </a>
    </li>
    <li class="communications" url="<?= URL_BASE.'index/comingsoom?page=communications&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left communications_left"></div>
            <div class="newmenu_bg communications_bg">
                <div style="padding-top:20px;">Communications</div>
            </div>
            <div class="newmenu_right communications_right"></div>
        </a>
    </li>
    <li class="reports" url="<?= URL_BASE.'index/comingsoom?page=reports&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left reports_left"></div>
            <div class="newmenu_bg reports_bg">
                <div style="padding-top:20px;">Reports</div>
            </div>
            <div class="newmenu_right reports_right"></div>
        </a>
    </li>
    <li class="adminstration" url="<?= URL_BASE.'index/comingsoom?page=adminstration&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left adminstration_left"></div>
            <div class="newmenu_bg adminstration_bg">
                <div style="padding-top:20px;">Administration</div>
            </div>
            <div class="newmenu_right adminstration_right"></div>
        </a>
    </li>
    <li class="schools" url="<?= URL_BASE.'index/comingsoom?page=schools&ajax=1' ?>">
        <a class="TabMenu" href= "#">
            <div class="newmenu_left schools_left"></div>
            <div class="newmenu_bg schools_bg">
                <div style="padding-top:20px;">ASSIST</div>
            </div>
            <div class="newmenu_right schools_right"></div>
        </a>
    </li>
</ul>
<input type="hidden" value="<?= $this->page ?>" id="hidSelectedMenu" />