<div id="confirmLayer" class="layercenter confirmLayer" style="display: none;">
    <div style="border: 1px thin;background-color: white;min-width: 300px;float: left;">
        <div id="popup_title" class="header">
            Header
        </div>
        <div style="padding: 5px;">
            <div class="message" style="float: left;width: 100%;min-height: 30px; padding: 10px 0px 5px 0px;">

            </div>
            <div style="float: right;padding-right: -5px;padding-bottom: 5px;">
                <input class="btnYes" type="button" value="Yes" />
            </div>
            <div style="float: right;padding-right: 5px;padding-bottom: 5px;">
                <input class="btnNo" type="button" value="No" />
            </div>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<div id="LoadingLayer" class="layercenterLoading" style="display: none;">
    <div class="message" >
        <img src="<?= URL_THEMES . 'img/loading.gif' ?>" />
    </div>
    <div style="clear: both;"></div>
</div>

<div id="msgLayer" class="layercenter confirmLayer" style="display: none;">
    <div style="border: 1px thin;background-color: white;min-width: 300px;float: left;">
        <div id="popup_title" class="header">
            Header
        </div>
        <div style="padding: 5px;">
            <div class="message" style="float: left;width: 100%;min-height: 30px; padding: 10px 0px 5px 0px;">

            </div>
            <div style="float: right;padding-right: 5px;padding-bottom: 5px;">
                <input class="btnNo" type="button" value="Cancel" />
            </div>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>


<div id="divSendEmail" style="display:none;" class="layercenter confirmLayer" style="top: 123px; left: 0;">
   
</div>
