<?php
$helper = $this->layout()->_helper;
$UserArray=$this->UserArray;
$getCandidates=$this->getCandidates;
//echo("<br><br><br>User:<pre>");print_r($UserArray);echo("</pre>");
?>
<style>

    ul#nav-left{margin:0;padding:7px 0;margin-bottom: 10px;list-style: none; border-top: 1px solid #bbb;border-bottom: 1px solid #bbb}
    ul#nav-left li{line-height: 35px;}
    ul#nav-left a{color: #777}
    ul#nav-left .active{color: #428bca}

        /****/
    .tree img{cursor: pointer}
    .tree-title{padding: 0 0 10px 40px;}
    .btn-default {
    background-color: #777;
    border-color: #ccc;
    color: #fff;
    }
    .btn-default:hover{
        background-color: #777;
        color: #fff;
    }
    .logo{
       /* background: url('<?=URL_THEMES?>images/avatar_none.jpg') no-repeat ;*/
       <?php
        $image=URL_MEDIA_PHOTO.$getCandidates["image"];
       ?>
       background: url('<?php if(!empty($getCandidates["image"])) echo  $image; else echo URL_THEMES."images/avatar_none.jpg";?>') no-repeat;
        width: 211px;
        height: 165px;
    }
     ul#nav-left {
    border-bottom: 2px solid #bbb;
    border-top: 2px solid #bbb;}
</style>
<?php

?>
<div class="container">

    <div class="row" style="padding-top: 40px;">
        <div class="col-md-3">
            <div class="text-center">
                 <div class="logo"><a href="<?= URL_BASE ?>candidate/upload-photo"><img src="<?=URL_THEMES?>images/bg_grey_text.png" style="float:right;padding-top:140px;"></a></div>

            </div>
            <a href="#"><?=$UserArray["emailaddress"]?></a><br/>
            <strong>View my profile</strong> <br/>
            <span>
                <img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span style="font-size:13px;padding-left:5px"><?=$UserArray["Country"]?><?php if($UserArray["Country"]=="") echo "United State";?></span><span style="padding-left:5px;font-size:13px" class=""><?=$UserArray["Address1"]?><?php if($UserArray["Address1"]!="") echo ", "; ?> <?=$UserArray["State"]?></span>
            </span>
            <span><strong>Expected Salary: <?=$getCandidates["minimumsalary"]?><?php if($getCandidates["minimumsalary"]!="") echo "-";?><?=$getCandidates["maximumsalary"]?><?php if($getCandidates["maximumsalary"]!="")echo "K";?></strong></span><br/>
            <p style="padding: 10px 0">
               <!-- <i class="lbl-log">Edit</i>-->
                 <a href="<?= URL_BASE ?>candidate/editoverview"><img src="<?=URL_THEMES?>images/btn_edit.png"></a>
            </p>
            <ul id="nav-left">
                <li><a href="<?=$helper->url('profile-builder?utm_source=contact','candidate');?>"><strong>Profile builder</strong></a></li>
                <li><a href="<?=$helper->url('profile','candidate');?>">Overview</a></li>
                <li><a href="<?=$helper->url('contact-info','candidate');?>">Contact Info</a></li>
                <li><a href="<?=$helper->url('portfolio','candidate');?>">Portfolio</a></li>
                <li><a href="<?=$helper->url('vieweducation','candidate');?>">Education</a></li>
                <li><a class="active" href="<?=$helper->url('skills?utm_source=index','candidate');?>"><strong>Skills</strong></a></li>
                <li><a href="#">References</a></li>
                <li><a href="#">Tests</a></li>
                <li><a href="#">Interest</a></li>
            </ul>
            <p style="font-size:13px;color:#777">Last signed: <?= date('M d, Y',strtotime($UserArray["Lastsigned"])) ?></p>
        </div>
        <div class="col-md-9">
            <div class="page-header" style="color: #2a6496 ;margin-top:0">
                <h2 style="color: #2a6496 ;margin-top:0"><span class=""></span> <strong>Skills Builder</strong></h2>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="tree-title">
                        <h4><strong> Click in Skills to go to individual Questionnaires</strong></h4>
                    </div>

                <div id="tree-lst">

                    <?=$this->tree;?>
                </div>
                <div class="col-md-12">
                    <div style="margin-top: 30px">
                      <!--  <button id="cmd-backview" data-back="" class="btn btn-default" type="button"><strong>Back</strong></button> &nbsp;-->
                        <button id="cmd-nextview" data-id="" type="button" data-next="" class="btn btn-success" type="button"><strong>Next</strong></button>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style type='text/css'>

    .tree {
        font-size: 12px;
        text-align: left;margin:0;padding:0;
    }
    .tree li {
        list-style-type:none;
        position:relative
    }
    .tree li::before, .tree li::after {
        content:'';
        left:-27px;
        position:absolute;
        right:auto
    }
    .tree li::before {
        border-left:1px dotted #999;
        bottom:50px;
        height:100%;
        top:0;
        width:1px
    }
    .tree li::after {
        border-top:1px dotted #999;
        height:20px;
        top:15px;
        width:25px
    }
    .tree li span {
       /*border-radius: 50%;
        border:1px dotted #999;
        display:inline-block;
        padding: 5px;
        text-decoration:none;
        color: #2a6496;*/
    }
    .tree li.parent_li>span {
        cursor:pointer
    }
    .tree>ul>li::before, .tree>ul>li::after {
        border:0
    }
    .tree li:last-child::before {
        height:30px
    }
    .tree li.parent_li>span:hover, .tree li.parent_li>span:hover+ul li span {
        background:#eee;
        border:1px dotted #94a0b4;

    }
    .tree .ico-expand{
        font-size: 11px !important;
        border-radius: 50%;
        border:1px dotted #999;
        display:inline-block;
        padding: 2px;
        text-decoration:none;
        color: #2a6496;
    }
    .tree .ico-colapse{
        border-radius: 50%;
        border:1px dotted #999;
        display:inline-block;
        padding: 5px;
        text-decoration:none;
        color: #2a6496;
    }
</style>

<script src="<?=URL_THEMES;?>js/pocket.candidate.js"></script>
 <script>
     var prCandidate= new pocketCandidate();
     prCandidate.editSkills('<?=URL_THEMES;?>');
     $('#cmd-nextview').unbind('click').bind('click',prCandidate.skillViewNext);
    // $('#cmd-backview').unbind('click').bind('click',prCandidate.skillViewBack);
</script>