<?php
    $UserArray=$this->UserArray;
    $getCandidates=$this->getCandidates;
    $Portfolio=$this->Portfolio;
    $ListImages=$this->ListImages;
    //print_r($ListImages);

?>
<style>
    body {
        background: none repeat scroll 0 0 #ededed;
    }
    ul#nav-left{margin:0;padding:7px 0;margin-bottom: 10px;list-style: none; border-top: 1px solid #bbb;border-bottom: 1px solid #bbb}
    ul#nav-left li{line-height: 35px;}
    ul#nav-left a{color: #777}
    ul#nav-left .active{color: #428bca}


    /****/

    .breadcrumb {
        width: 100%;
        /*centering*/
        padding:3px;
        border: 1px solid #ddd;
        display: inline-block;
        /*box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.35);*/
        /*overflow: hidden;*/
        /*border-radius: 5px;*/
        /*Lets add the numbers for each link using CSS counters. flag is the name of the counter. to be defined using counter-reset in the parent element of the links*/
        counter-reset: flag;
    }

    .breadcrumb a {
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        outline: none;
        display: block;
        float: left;
        font-size: 12px;
        line-height: 36px;
        color: white;
        /*need more margin on the left of links to accomodate the numbers*/
        padding: 0 30px;
        background: #666;
        background: linear-gradient(#666, #333);
        position: relative;
    }
        /*since the first link does not have a triangle before it we can reduce the left padding to make it look consistent with other links*/
    .breadcrumb a:first-child {
        padding-left: 46px;
        border-radius: 5px 0 0 5px; /*to match with the parent's radius*/
    }
    .breadcrumb a:first-child:before {
        left: 14px;
    }
    .breadcrumb a:last-child {
        border-radius: 0 5px 5px 0; /*this was to prevent glitches on hover*/
        padding-right: 20px;
    }

        /*hover/active styles*/
    .breadcrumb a.active, .breadcrumb a:hover{
        background: #333;
        background: linear-gradient(#333, #000);
    }
    .breadcrumb a.active:after, .breadcrumb a:hover:after {
        background: #333;
        background: linear-gradient(135deg, #333, #000);
    }

        /*adding the arrows for the breadcrumbs using rotated pseudo elements*/
    .breadcrumb a:after {
        content: '';
        position: absolute;
        top: 0;
        right: -18px; /*half of square's length*/
        /*same dimension as the line-height of .breadcrumb a */
        width: 36px;
        height: 36px;
        transform: scale(0.707) rotate(45deg);
        /*we need to prevent the arrows from getting buried under the next link*/
        z-index: 1;
        /*background same as links but the gradient will be rotated to compensate with the transform applied*/
        background: #666;
        background: linear-gradient(135deg, #666, #333);
        /*stylish arrow design using box shadow*/
        box-shadow:
            /*2px -2px 0 2px rgba(0, 0, 0, 0.4),3px -3px 0 2px rgba(255, 255, 255, 0.1);*/
            2px -2px 0 2px #bbb,
            3px -3px 0 2px #eee;
        border-radius: 0 5px 0 50px;
    }
        /*we dont need an arrow after the last link*/
    .breadcrumb a:last-child:after {
        content: none;
    }
        /*we will use the :before element to show numbers*/
    .breadcrumb a:before {
        border-radius: 100%;
        width: 20px;
        height: 20px;
        line-height: 20px;
        margin: 8px 0;
        position: absolute;
        top: 0;
        left: 30px;
        background: #444;
        background: linear-gradient(#444, #222);
        font-weight: bold;
    }


    .flat a, .flat a:after {
        background: white;
        color: black;
        transition: all 0.5s;
    }
    .flat a:before {
        background: white;
        box-shadow: 0 0 0 1px #ccc;
    }
    .flat a:hover, .flat a.active,
    .flat a:hover:after, .flat a.active:after{
        background: #2a6496; color: #fff;
    }
    .page-header {
        border-bottom: 2px solid #d6d6d6;
    }
    
    .well{
        background-color: #f5f5f5;
        border: 1px solid none;
        margin-bottom: 0;
        padding: 0;
    }
    .label-tag {
        border: 1px solid #ddd;
        padding: 3px;
        background-color: #fff;
        color: #000;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
        margin-right: 10px;
        margin-bottom: 5px;
    }
    #requiredTest {
        min-height: 200px; 
        height:auto;
        border: 1px solid #cccccc;
    }
   
    .logo{
       /* background: url('<?=URL_THEMES?>images/avatar_none.jpg') no-repeat ;*/
       <?php
        $image=URL_MEDIA_PHOTO.$getCandidates["image"];
       ?>
       background: url('<?php if(!empty($getCandidates["image"])) echo  $image; else echo URL_THEMES."images/avatar_none.jpg";?>') no-repeat;
        width: 211px;
        height: 165px;
    }
    .lbl-log {
        color:black;
    }
    .btn-success1 {
    background-color: #2a6496;
    
    border-color: #2B59A9;
    color: #fff;
    }
    .btn-success1:hover, .btn-success1:focus, .btn-success1:active,.btn-success1.active {
    background-color: #2a6496;
    border-color: #2B59A9;
    color: #fff;
    }
    .btn-sm, .btn-group-sm > .btn {
    border-radius: 5px;
    font-size: 15px;
    font-weight: bold;
    line-height: 1.5;
    padding: 6px 15px;
    }

    #img{
    width:20px;
    border:none;
    height:20px;
    margin-left:-20px;
    margin-bottom:80px
    }
    
    .abcd img{
    height:100px;
    width:100px;
    padding:5px;
    border:1px solid #e8debd
    }
        /****/

</style>
<script src="<?=URL_THEMES.'js/portfolio.js';?>"></script>



<div class="container" style="padding-top:40px;">

    <div class="row">
        <div class="col-md-3">
            <div class="text-center">
              
               <div class="logo"><a href="<?= URL_BASE ?>candidate/upload-photo"><img src="<?=URL_THEMES?>images/bg_grey_text.png" style="float:right;padding-top:140px;"></a></div>
            </div>
            <span  style="font-size: 12px;color: #005595;"><?= $UserArray["emailaddress"]?></span><br/>
            <span style="font-weight:bold">View my profile</span> <br/>
            <span>
                <img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span style="font-size:13px;padding-left:5px"><?=$UserArray["Country"]?></span><span style="padding-left:5px;font-size:13px" class=""><?=$UserArray["Address1"]?><?php if($UserArray["Address1"]!="") echo ", ";?><?=$UserArray["State"]?></span>
            </span>
            <span><strong>Expected Salary: <?=$getCandidates["minimumsalary"]?><?php if($getCandidates["minimumsalary"]!="") echo "-";?><?=$getCandidates["maximumsalary"]?><?php if($getCandidates["maximumsalary"]!="") echo"K";?></strong></span><br/>
            <p style="padding: 10px 0">
                <!--<i class="lbl-log">Edit</i>>-->
                <a href="<?= URL_BASE ?>candidate/editoverview"><img src="<?=URL_THEMES?>images/btn_edit.png"></a>
            </p>
            <ul id="nav-left">
                <li><a href="<?= URL_BASE ?>candidate/profile-builder?utm_source=contact">Profile builder</a></li>
                <li><a href="<?= URL_BASE ?>candidate/profile">Overview</a></li>
                <li><a href="<?= URL_BASE ?>candidate/contact-info">Contact Info</a></li>
				<li><a href="<?= URL_BASE ?>candidate/employment">Employment</a></li>
                <li><strong><a href="<?= URL_BASE ?>candidate/portfolio" class="active">Portfolio</a></strong></li>
                <li><a href="<?= URL_BASE ?>candidate/vieweducation">Education</a></li>
                <li><a href="<?= URL_BASE ?>candidate/skills?utm_source=index">Skills</a></li>
                <li><a href="#">References</a></li>
                <li><a href="<?= URL_BASE ?>candidate/skilltest">Tests</a></li>
                <li><a href="<?= URL_BASE ?>candidate/interest">Interest</a></li>
            </ul>
            <p style="font-size:13px;color:#777">Last signed: <?= date('M d, Y',strtotime($UserArray["Lastsigned"])) ?></p>
        </div>
        <div class="col-md-9" >
            <div class="page-header" style="margin:0;">
            
                <span class="text-left" style="font-size: 30px;color: #005595;font-weight:bold">Portfolio</span>
                
                
             </div>
             
            <div class="">
                <div class="panel-body" style="padding:0;">

                    <div class="col-md-8"  style="padding:0;margin-top:1px;margin-botton:50px;border-radius: 10px;">
                    <form id="portfolio-form"  style="font-size:12px" enctype="multipart/form-data" method="post" action="<?= URL_BASE ?>candidate/do-updateportfolio">
                            <div class="form-group">
                                <input name="CandidatePortfolioID" id="CandidatePortfolioID" type="hidden" class="form-control"  value="">
                             
                            </div>
                            <div class="form-group">
                                <label>Title</label>
                                <input name="CandidatePortfolioID" id="CandidatePortfolioID" type="hidden" class="form-control"  value="<?=$Portfolio["CandidatePortfolioID"]?>">
                                <input name="Title" id="Title" type="text" class="form-control"  value="<?=$Portfolio["Title"]?>">
                            </div>
                            <div class="form-group">
                                <label>URL (if any)</label>
                                <input name="URL" id="URL"  type="text" class="form-control" value="<?=$Portfolio["URL"]?>">
                            </div>
                            
                              <div class="form-group" style="height:180px">
                              
                                    <label> <strong>Images (if any)</strong></label><br>
                                        
                                         <div id="filediv">
                                         <table id="portfolioList"><tr>
                                         <?php
                                         if(!empty($ListImages)||$ListImages!=""){
                                         foreach($ListImages as $images)
                                         {

                                         ?>
                                         <td><div class="abcd"><img data-id="<?=$images["ID"]?>" width="100px" height="100px" style='border: 1px solid rgb(232, 222, 189)' src="<?=URL_MEDIA_PORTFOLIO.$images["images"];?>" ><a id="port-deletes1" data-id="<?=$images["ID"]?>" style="cursor:pointer" ><img data-id="<?=$images["ID"]?>" id="img" src="<?=URL_THEMES?>images/ico_del.png" style="width: 20px; height: 20px;" alt="delete"></a></div></td>
                                         <?php
                                         }}else{
                                         ?>
                                         <td id="tetst"><img width="100px" height="100px" src="<?=URL_THEMES.'images/avatar_none.jpg';?>"><img id="img" src="<?=URL_THEMES?>images/ico_del.png" style="width: 20px; height: 20px;" alt="delete"></td>
                                         <?php
                                         }
                                         ?>
                                         </tr></table></div>
                                         <input type="button" id="add_more" class="upload" value="Add More Files"/>
                            </div>
                            
                           
                             <div class="form-group">
                                
                                    <label> <strong>Description</strong></label><br>
                                    <textarea rows="6" class="form-control" name="Description" id="Description"><?=$Portfolio["Description"]?></textarea>
                                    
                                    
                                
                            </div>
                            <div class="form-group">
                            <input class="btn btn-sm btn-success1" type="submit" id="AddPorfolio" name="AddPorfolio" value="Save" style="margin-right:5px">
                            <input class="btn btn-sm btn-success1" type="submit" id="AddAndAnothorPortfolio" name="AddAndAnothorPortfolio" value="Save and Add Another" style="margin-right:5px">  
                               
                                <img src="<?=URL_THEMES.'images/btn_Cacel.png';?>" id="Cancle" style="cursor:pointer;height:37px" onclick="document.location='portfolio'">
                                
                            </div>
                        </form> 
                       
                        

                    </div>                     
                    <div style="padding-top:20px;">
                         
                         </div>
                                            

                </div>
            </div>
            <div style="padding-top:40px;">
            </div>
        </div>
    </div>
</div>

<script>
    var prCandidate= new pocketCandidate();
  //  $('#portfolioList a').unbind('click').bind('click',prCandidate.deleteimage);
    
    var abc = 0;      // Declaring and defining global increment variable.
$(document).ready(function() {
//  To add new input file field dynamically, on click of "Add More Files" button below function will be executed.
//$('#img').click(function() {
//$(this).parent().parent().remove();
//});
$('#add_more').click(function() {
$(this).before($("<div/>", {
id: 'filediv'
}).fadeIn('slow').append($("<input/>", {
name: 'file[]',
type: 'file',
id: 'file'
}), 
$("")
));
});
// Following function will executes on change event of file input to select different file.
var file=$('#portfolio-form').find('[name="file[]"]');

//$('body').on('change', '#file', function() {
$('body').on('change', '#file', function() {
    //console.log(file);
if (this.files && this.files[0]) {

abc += 1; // Incrementing global variable by 1.
var z = abc - 1;
var x = $(this).parent().find('#previewimg' + z).remove();
$("tr").append("<td><div id='abcd" + abc + "' class='abcd'><img width='100px' heigh='100px' style:'border: 1px solid rgb(232, 222, 189)' id='previewimg" + abc + "' src=''/></div></td>");
var reader = new FileReader();
reader.onload = imageIsLoaded;
reader.readAsDataURL(this.files[0]);
$("#tetst").hide();
$(this).hide();
$("#abcd" + abc).append($("<img/>", {
id: 'img',
src: '<?=URL_THEMES?>images/ico_del.png',
width:'20px',
height:'20px',
alt: 'delete'
}).click(function() {
$(this).parent().parent().remove();
}));
}
});
// To Preview Image
function imageIsLoaded(e) {
$('#previewimg' + abc).attr('src', e.target.result);
};
$('#upload').click(function(e) {
var name = $(":file").val();
if (!name) {
alert("First Image Must Be Selected");
e.preventDefault();
}
});
});
</script>