<?php
$helper = $this->layout()->_helper;
$UserArray=$this->UserArray;
$getCandidates=$this->getCandidates;
$Skills=$this->Skills;
//echo("<br><br><br>User:<pre>");print_r($Skills);echo("</pre>");
?>
<style>

    ul#nav-left{margin:0;padding:7px 0;margin-bottom: 10px;list-style: none; border-top: 1px solid #bbb;border-bottom: 1px solid #bbb}
    ul#nav-left li{line-height: 35px;}
    ul#nav-left a{color: #777}
    ul#nav-left .active{color: #428bca}

        /****/
    .tree img{cursor: pointer}
    .tree-title{padding: 0 0 10px 40px;}
    /*.btn-default {
       background-color: #777;
        border-color: #ccc;
        color: #fff;
        }
    .btn-default:hover{
        background-color: #777;
        color: #fff;
    }*/
    .logo{
       /* background: url('<?=URL_THEMES?>images/avatar_none.jpg') no-repeat ;*/
       <?php
        $image=URL_MEDIA_PHOTO.$getCandidates["image"];
       ?>
       background: url('<?php if(!empty($getCandidates["image"])) echo  $image; else echo URL_THEMES."images/avatar_none.jpg";?>') no-repeat;
        width: 211px;
        height: 165px;
    }
     ul#nav-left {
    border-bottom: 2px solid #bbb;
    border-top: 2px solid #bbb;}
    .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
        color:#2a6496;
    }
    ul.test-list-item{
        margin:0;padding:0;list-style: none;
    }
    btn1 {
    border-radius: 3px;
    font-size: 12px;
    line-height: 1.5;
    padding: 5px 10px;
    width: 50px;
}
.btn-group{
    width: 400px;
}
 .dropdown-menu {
  min-width:70px;
  }
  .qst-remove{cursor: pointer;color: #ccc}
    .qst-remove:hover{color: #333}
</style>

<?php

?>
<div class="container">

    <div class="row" style="padding-top: 40px;">
        <div class="col-md-3">
            <div class="text-center">
                 <div class="logo"><a href="<?= URL_BASE ?>candidate/upload-photo"><img src="<?=URL_THEMES?>images/bg_grey_text.png" style="float:right;padding-top:140px;"></a></div>

            </div>
            <a href="#"><?=$UserArray["emailaddress"]?></a><br/>
            <strong>View my profile</strong> <br/>
            <span>
                <img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span style="font-size:13px;padding-left:5px"><?=$UserArray["Country"]?><?php if($UserArray["Country"]=="") echo "United State";?></span><span style="padding-left:5px;font-size:13px" class=""><?=$UserArray["Address1"]?><?php if($UserArray["Address1"]!="") echo ", "; ?> <?=$UserArray["State"]?></span>
            </span>
            <span><strong>Expected Salary: <?=$getCandidates["minimumsalary"]?><?php if($getCandidates["minimumsalary"]!="") echo "-";?><?=$getCandidates["maximumsalary"]?><?php if($getCandidates["maximumsalary"]!="")echo "K";?></strong></span><br/>
            <p style="padding: 10px 0">
                <!--<i class="lbl-log">Edit</i>-->
                 <a href="<?= URL_BASE ?>candidate/editoverview"><img src="<?=URL_THEMES?>images/btn_edit.png"></a>
            </p>
            <ul id="nav-left">
                <li><a href="<?=$helper->url('profile-builder?utm_source=contact','candidate');?>"><strong>Profile builder</strong></a></li>
                <li><a href="<?=$helper->url('profile','candidate');?>">Overview</a></li>
                <li><a href="<?=$helper->url('contact-info','candidate');?>">Contact Info</a></li>
                <li><a href="<?=$helper->url('portfolio','candidate');?>">Portfolio</a></li>
                <li><a href="<?=$helper->url('vieweducation','candidate');?>">Education</a></li>
                <li><a href="<?=$helper->url('skills?utm_source=index','candidate');?>">Skills</a></li>
                <li><a href="#">References</a></li>
                <li><a href="<?=$helper->url('skilltest','candidate');?>">Tests</a></li>
                <li><a class="active" href="#"><strong>Interest</strong></a></li>
            </ul>
            <p style="font-size:13px;color:#777">Last signed: <?= date('M d, Y',strtotime($UserArray["Lastsigned"])) ?></p>
        </div>
        <div class="col-md-9">
            <div class="page-header" style="color: #2a6496 ;margin-top:0">
                <h2 style="color: #2a6496 ;margin-top:0"><span class=""></span> <strong>Interest</strong></h2>
            </div>
            
                <div class="panel-body" style="padding:0">
				<div class="col-md-8" style="padding:0">
				  <form id="Interest-form"  style="font-size:12px"  role="form" >
				   <div class="form-group">
					<label>Add Interest</label>
					<input type="hidden" name="interestid" id="interestid" />
					<input name="interest" id="interest" type="text" class="form-control"  value="">
					  
					</div>	
					<div style="float:right"><button class="btn btn-default" id="addInterest" data-status="add"><strong>+Add</strong></button></div>
				</form>		
					
                  </div>
				<div>	
                <div class="col-md-12" id="" style="font-size:12px;padding:0;padding-top:20px">
				

				<div class="panel panel-default" style="margin:0">
					<div class="panel-heading" style="background-color: #2a6496;color: #fff">
						<h4 class="panel-title" style="font-size:12px">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
								<strong>Interest</strong>
							</a>
						</h4>
					</div>

				</div>
				 <!-- Interest list-->
        <div class="tab-pane active" style="padding:0" >
            <table id="test-list" class="table table-striped  table-stripedgray table-bordered" cellspacing="0" width="100%" style="border-top-color: #eeeeee">
                <thead height="34px" style="height:34px">
                <tr role="row" style="background-color: #eeeeee" height="34px">
                    <th  width="640px" >
                        
                            <input id="Index-Check-All" type="checkbox" name="" value=""/><strong style="padding-left:10px">Select All</strong>
                        
                    </th>
                    <th>
                        <div class="btn-group" style="width:50px;padding:0">
                            <span class="pull-left"><span class="dropdown">
                                       Action<span style="cursor:pointer; width:10px; height:2px" data-toggle="dropdown" class="caret"></span>
                                        <ul  class="dropdown-menu" role="menu">
                                            <li><a  href="javascript: void(0)" id="test-edit">Edit</a></li>
                                            <li><a href="javascript: void(0)" id="test-act-remove">Delete</a></li>
                                            <!--<li><a data-toggle="modal" data-target="#are-you-sure-you-want-to-delete" href="javascript: void(0);">Delete</a></li>-->
                                        </ul>
                                    </span></span>
                            
                        </div>
                    </th>
                    
                </tr>
                </thead>
                <tbody style="background-color: #f9f9f9;">
               
						<?php
							if(!empty($this->listInterest)){
								foreach($this->listInterest as $listInterest){
						?>
						<tr role="row"> 
						
							<td>
								
                               <input type="checkbox" data-text="<?=$listInterest["interesttext"];?>" data-id="<?=$listInterest["interestid"]?>" value="<?=$listInterest["interestid"]?>" class="Index-Is-Check" /><span style="padding-left:10px"><?=$listInterest["interesttext"]?> </span>
                            </td>
							<td><img data-id="<?=$listInterest["interestid"]?>" data-text="<?=$listInterest["interesttext"]?> " style="height:15px; width:15px;" src="<?=URL_THEMES?>images/ico_del.png" class="qst-remove" id="qst-remove"></td>
						
						
						</tr>
						<?php
								}
							}
						?>
                   
                </tbody>
            </table>


        </div>
        <!--Interest list end-->
				</div>
                  
                </div>
                
            </div>
        </div>
    </div>
</div>


<script src="<?=URL_THEMES;?>js/pocket.interest.js?vs=1"></script>
 <script>
     var prInterest= new pocketInterest();
	 $('#Index-Check-All').unbind('click').bind('click',prInterest.IndexCheckedAll)
	 $('#test-act-remove').unbind('click').bind('click',prInterest.testRemoveInt)
	 $('#addInterest').unbind('click').bind('click',prInterest.interestCreate);
    
</script>