<script src="<?=URL_THEMES.'js/pocket.candidate.js?vs=1';?>"></script>
<script>
    var objMatch = new pocketCandidate();
</script>
<style>

    .borderbottom_Gray {
        border-bottom: 1px solid #ccc;
    }

    .border_radius_careermatch {
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
        color: #555;
        display: block;
        font-size: 14px;
        line-height: 1.42857;
        width: 90px;
    }
    .label-tag{
        border: 1px solid #ddd; padding: 3px;
        background-color: #eee;
        color: #000;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        margin-right: 10px;margin-bottom: 5px;
    }

</style>
<script>
    var urlImage = '<?=URL_THEMES;?>';
</script>

<!--Modal-->
<div class="modal fade" tabindex="-1" role="dialog" id="match-opp-skills-id" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content modal-dialog-center">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title" id="myModalLabel">Select Skill</h2>
            </div>
            <div class="modal-body login-modal">
                <div class="col-md-12">
                    <div class="form-group">
                        <select id="add-opp-skills" class="form-control">
                            <option value="">Select Skill</option>
                            <?php
                            $SkillList = $this->skillList;
                            foreach ($SkillList as $k=>$skillInfo) {
                                ?>
                                <option value="<?=$skillInfo['SkillID']?>" ><?=$skillInfo['SkillName']?></option>
                            <?php
                            }

                            ?>
                        </select>
                    </div>
                </div>
                <button style="background-color:#fff; border:#fff">&nbsp;</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="this-job-was-applied" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-sm">
        <div class="modal-content modal-dialog-center">
            <div class="modal-header" style="border-bottom: none">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <div class="modal-title text-center" id="modal-this-job-was-applied"></div>
            </div>
        </div>
    </div>
</div>
<!--END-->
<div class="container" style="margin-top: 10px">

    <div style="color: #2a6496;margin-bottom:11px; border-bottom: 2px solid #d6d6d6;" class="col-md-12">
        <div class="col-md-12" style="margin-top: 25px;">
            <h3 style="margin-left: -30px; margin-bottom: 0px"><label>Match Opportunities</label> </h3>
        </div>

    </div>

    <?php
    $oppList = $this->oppList;
    ?>

    <div class="col-md-12" style="padding-left: 0px; padding-right: 0px; border: 1px #ccc solid; min-height: 280px; background-color: #fff">
        <form id="form-match-opportunity-sear" name="form-match-opportunity-sear">
            <div style="margin-top: 15px"><span class="caret11" style="float:right; margin-right: 8px"></span></div>
            <div class="col-md-12" style="margin-top:0px">
                <div class="col-md-6">
                    <select class="form-control" name="technology_id">
                        <option value="" style="color: red!important" >Select Industry</option>
                        <?php
                        if($this->industryList !=""){
                            foreach ($this->industryList as $industry) {
                                ?>
                                <option value="<?=$industry?>"><?=$industry?></option>
                            <?php
                            }
                        }
                        ?>
                    </select>
                </div>
                <div class="col-md-2">
                    <select class="form-control" name="experience_name">
                        <option value="">Select Experience</option>
                        <?php
                        if($this->experienced_List !=""){
                            foreach ($this->experienced_List  as $ek=>$experiencedInfo){ ?>
                                <option value="<?=$experiencedInfo['experience_id']?>" ><?=$experiencedInfo['experience_descrip']?></option>
                            <?php
                            }
                        }
                        ?>

                    </select>
                </div>
                <div class="col-md-2">
                    <select class="form-control" name="country_name">
                        <option value="">Select Country</option>
                        <?php
                        if($this->country_List !=""){
                            foreach ($this->country_List  as $kc=>$countryInfo){ ?>
                                <option value="<?=$countryInfo['code']?>" ><?=$countryInfo['name']?></option>
                            <?php
                            }
                        }
                        ?>

                    </select>
                </div>
                <div class="col-md-2">
                    <select class="form-control" name="city_name">
                        <option value="">Select City</option>
                        <?php
                        if($this->city_List !=""){
                            foreach ($this->city_List  as $cityInfo){
                                ?>
                                <option value="<?=$cityInfo?>" ><?=$cityInfo?></option>
                            <?php
                            }
                        }
                        ?>

                    </select>
                </div>


            </div>
            <div class="col-md-12" style="padding-left: 28px; margin-top:15px"><label>Skills</label></div>
            <div class="col-md-12" style="padding-left:30px; padding-right:30px" >
                <div class="form-control" id="match-opp-skills" style="min-height: 80px"></div>
            </div>
            <div class="col-md-12">

            </div>
            <div class="col-md-12" style="margin-top:15px">
                <div class="col-md-10"> </div>
                <div class="col-md-2"><button class="btn btn-sm btn-default" style="float:right; margin-right: 0px; font-weight: bold; background-color: #fff; color: #2a6496"  type="button" data-target="#match-opp-skills-id" data-toggle="modal">+&nbsp; Add Skills</button></div>
            </div>
            <div class="col-md-12" style="margin-top:15px;">
                <div class="col-md-2">
                    <button class="btn btn-sm btn-default  btn-primary" CandidateProfileID="<?=$this->CandidateProfileID?>" onclick="javascript:objMatch.matchOpportunities(<?=$this->CandidateProfileID?>)" style=" margin-right: 0px; font-weight: bold;"  type="button">Match</button>
                </div>
                <div class="col-md-10"></div>
            </div>
        </form>
    </div>

    <div class="col-md-12" style="background-color: #fff; min-height:374px; height: auto;border: 1px solid #ccc; margin-top: 20px">
        <div style="height: 20px!important;"></div>
        <!-- table-->
        <table border="0" style="width: 100%">
            <tr>
                <td style="width:220px; border-right:1px solid #ccc;vertical-align: top  ">
                    <div class="col-md-12" style="margin-top:-2px;">
                        <div><label>All Catogories</label></div>
                        <div><label style="color: #1a5187">IT & Programming</label></div>
                        <div>Design & Multimedia</div>
                        <div>Writing & Translation</div>
                        <div>Sale & Marketing</div>
                        <div>Admin Support</div>
                    </div>

                    <div class="col-md-12" style="margin-top:20px;">
                        <div><label>All Career Types</label></div>
                        <div>Fixed Price</div>
                        <div>Hourly</div>
                    </div>

                    <div class="col-md-12" style="margin-top:20px;">
                        <div><label>Any Budget</label></div>
                        <div>Specific Budget</div>
                    </div>

                    <div class="col-md-12" style="margin-top:20px;">
                        <div><label>All Locations</label></div>
                        <div>Region</div>
                        <div>Country</div>
                        <div>Specific Location</div>
                    </div>
                    <div class="col-md-12" style="margin-top:20px;">
                        <div><label>Any Time Left</label></div>
                        <div>Less than 24 hours left</div>
                        <div>Less than 3 days left</div>
                        <div>Less than 7 days left</div>
                    </div>
                    <div class="col-md-12" style="margin-top:20px;">
                        <div><label>Any Posted Date</label></div>
                        <div>Posted within 24 hours</div>
                        <div>Posted within 3 days</div>
                        <div>Posted within 7 days</div>
                    </div>
                    <div class="col-md-12" style="margin-top:20px;">
                        <div><label>All Career Options</label></div>
                        <div class="col-md-12" style="padding-left: 0px;padding-right: 0px">
                            <div class="col-md-5" style="margin-left: -15px"><input type="checkbox"> Only</div>
                            <div class="col-md-6 border_radius_careermatch"><strong style="color: #1a5187">Featured</strong></div>
                        </div>

                    </div>
                    <div class="col-md-12" style="margin-top:20px;">
                        <div><label>Status Open</label></div>
                        <div style="color: #1a5187; font-weight: bold">Any Status</div>
                        <div>Hiring Open</div>
                    </div>
                    <div class="col-md-12" style="margin-top:20px;">
                        <div><label>Group</label></div>
                        <div style="color: #1a5187; font-weight: bold">No Group</div>
                        <div>Selected Group</div>
                    </div>
                </td>
                <td style="vertical-align: top" class="containerData">

                </td>
            </tr>
        </table>

        <!-- table -->
    </div>
    <div style="clear: both"></div>
    <div style="height: 40px;background-color: #333"> </div>
</div>
<script>
    $(document).ready(function(){
        $("#add-opp-skills").unbind("change").bind("change",objMatch.addOppSkillsToSearch)
        $(".btn-for-apply").unbind("click").bind("click",objMatch.candidateApply)
        objMatch.matchOpportunities(<?=$this->CandidateProfileID?>)
        $("#nav li").removeClass("active");
        $('#Opportunities').addClass('active'); 
    })
</script>













