
<!--<header class="subhead" id="overview">-->
    <div class="panel panel-primary" style="border:0">
        <div class="panel-heading">
                <h3 class="panel-title">
                    <strong>Profile Builder</strong>
                    
                </h3>
            </div>
            <div class="panel-body">
            
        
                <h3 class="panel-title">
                    <strong>In Progress</strong>
                    
                </h3>
        
        </div>
    </div>
<!--</header>-->
<!-- jQuery Version 1.11.0 -->



<script type="text/javascript">
 $(document).ready(function () {
         $('#Email1').blur(function () {
         var error = false; 
         if($('#Email1').val()!=='')
         {
            
            var x = $('#Email1').val();
            var atpos = x.indexOf("@");
            var dotpos = x.lastIndexOf(".");
            
            if(atpos<1 || dotpos<atpos+2 || dotpos+2>=x.length){
                error = true;
                $("#Email1_message").addClass('has-error');
                $("#Email1_message").html("The primary mail is not a valid email address");
                }else{
                $("#Email1_message").removeClass('has-error').addClass('has-success');
                $("#Email1_message").html('');
            }  
         }
             
             
        });
 });
</script>
