<?php
    $getUserArray=$this->client;
    $getCandidates=$this->getCandidates;
    $SkillName=$this->SkillName;
    $CandidateEmployment=$this->CandidateEmployment;
    $Education=$this->Education;
 // echo ("<br><br><br>test:<pre>");print_r($Education);echo("</pre>");
?>
<style>
    body {
    background: none repeat scroll 0 0 #ededed;
    }
    ul#nav-left{margin:0;padding:7px 0;margin-bottom: 10px;list-style: none; border-top: 1px solid #bbb;border-bottom: 1px solid #bbb}
    ul#nav-left li{line-height: 35px;}
    ul#nav-left a{color: #777}
    ul#nav-left .active{color: #428bca}


    /****/

    .breadcrumb {
        width: 100%;
        /*centering*/
        padding:3px;
        border: 1px solid #ddd;
        display: inline-block;
        /*box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.35);*/
        /*overflow: hidden;*/
        /*border-radius: 5px;*/
        /*Lets add the numbers for each link using CSS counters. flag is the name of the counter. to be defined using counter-reset in the parent element of the links*/
        counter-reset: flag;
    }

    .breadcrumb a {
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        outline: none;
        display: block;
        float: left;
        font-size: 12px;
        line-height: 36px;
        color: white;
        /*need more margin on the left of links to accomodate the numbers*/
        padding: 0 30px;
        background: #666;
        background: linear-gradient(#666, #333);
        position: relative;
    }
        /*since the first link does not have a triangle before it we can reduce the left padding to make it look consistent with other links*/
    .breadcrumb a:first-child {
        padding-left: 46px;
        border-radius: 5px 0 0 5px; /*to match with the parent's radius*/
    }
    .breadcrumb a:first-child:before {
        left: 14px;
    }
    .breadcrumb a:last-child {
        border-radius: 0 5px 5px 0; /*this was to prevent glitches on hover*/
        padding-right: 20px;
    }

        /*hover/active styles*/
    .breadcrumb a.active, .breadcrumb a:hover{
        background: #333;
        background: linear-gradient(#333, #000);
    }
    .breadcrumb a.active:after, .breadcrumb a:hover:after {
        background: #333;
        background: linear-gradient(135deg, #333, #000);
    }

        /*adding the arrows for the breadcrumbs using rotated pseudo elements*/
    .breadcrumb a:after {
        content: '';
        position: absolute;
        top: 0;
        right: -18px; /*half of square's length*/
        /*same dimension as the line-height of .breadcrumb a */
        width: 36px;
        height: 36px;
        
        transform: scale(0.707) rotate(45deg);
        /*we need to prevent the arrows from getting buried under the next link*/
        z-index: 1;
        /*background same as links but the gradient will be rotated to compensate with the transform applied*/
        background: #666;
        background: linear-gradient(135deg, #666, #333);
        /*stylish arrow design using box shadow*/
        box-shadow:
            /*2px -2px 0 2px rgba(0, 0, 0, 0.4),3px -3px 0 2px rgba(255, 255, 255, 0.1);*/
            2px -2px 0 2px #bbb,
            3px -3px 0 2px #eee;
        
        border-radius: 0 5px 0 50px;
    }
        /*we dont need an arrow after the last link*/
    .breadcrumb a:last-child:after {
        content: none;
    }
        /*we will use the :before element to show numbers*/
    .breadcrumb a:before {
       
        border-radius: 100%;
        width: 20px;
        height: 20px;
        line-height: 20px;
        margin: 8px 0;
        position: absolute;
        top: 0;
        left: 30px;
        background: #444;
        background: linear-gradient(#444, #222);
        font-weight: bold;
    }


    .flat a, .flat a:after {
        background: white;
        color: black;
        transition: all 0.5s;
    }
    .flat a:before {
        background: white;
        box-shadow: 0 0 0 1px #ccc;
    }
    .flat a:hover, .flat a.active,
    .flat a:hover:after, .flat a.active:after{
        background: #2a6496; color: #fff;
    }
    .page-header {
        border-bottom: 2px solid #d6d6d6;
    }
    .line-r{
         border-right: 1px solid #d6d6d6;
         padding-right: 10px;
         height: 10px;
    
    }
    .line-l{
         border-left: 1px solid #d6d6d6;
         padding-left: 5px;
         height: 10px;
    
    }
    .well{
        margin-bottom: 0;
        padding:0;
    }
    .label-tag {
        border: 1px solid #ddd;
        padding: 3px;
        background-color: #fff;
        color: #000;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
        margin-right: 10px;
        margin-bottom: 5px;
    }
    .logo{
       /* background: url('<?=URL_THEMES?>images/avatar_none.jpg') no-repeat ;*/
       <?php
        $image=URL_MEDIA_PHOTO.$getCandidates["image"];
       ?>
       background: url('<?php if(!empty($getCandidates["image"])) echo  $image; else echo URL_THEMES."images/avatar_none.jpg";?>') no-repeat;
        width: 211px;
        height: 165px;
    }
    ul#nav-left {
    border-bottom: 2px solid #bbb;
    border-top: 2px solid #bbb;}
    audio, canvas, progress, video {
        width: 230px;
    }
        /****/

</style>

<div class="container" style="padding-top:40px;">

    <div class="row">
     <div class="col-md-3">
        <div class="text-center">
          <div class="logo"><a href="<?= URL_BASE ?>candidate/upload-photo"><img src="<?=URL_THEMES?>images/bg_grey_text.png" style="float:right;padding-top:140px;"></a></div>

            </div>
            <span  style="font-size: 12px;color: #005595;"><?= $getUserArray["emailaddress"]?></span><br/>
            <span style="font-weight:bold;font-size:13px">View my profile</span> <br/>
            <span>
                <img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span style="font-size:13px;padding-left:5px"><?=$getUserArray["Country"]?><?php if($getUserArray["Country"]=="") echo "United State";?></span><span style="padding-left:5px;font-size:13px" class=""><?=$getUserArray["Address1"]?><?php if($getUserArray["Address1"]!="") echo ", "; ?> <?=$getUserArray["State"]?></span>
            </span>
            <br><span><strong style="font-size:13px">Expected Salary: <?=$getCandidates["minimumsalary"]?><?php if($getCandidates["minimumsalary"]!="") echo "-";?><?=$getCandidates["maximumsalary"]?><?php if($getCandidates["maximumsalary"]!="")echo "K";?></strong></span><br/>
            <p style="padding: 10px 0">
                <!--<i class="lbl-log">Edit</i>>-->
                <a href="<?= URL_BASE ?>candidate/editoverview"><img src="<?=URL_THEMES?>images/btn_edit.png"></a>
            </p>
            <ul id="nav-left">
                <li><a href="<?= URL_BASE ?>candidate/profile-builder?utm_source=contact">Profile builder</a></li>
                <li><strong><a class="active" href="<?= URL_BASE ?>candidate/profile">Overview</a></strong></li>
                <li><a href="<?= URL_BASE ?>candidate/contact-info">Contact Info</a></li>
                <li><a href="<?= URL_BASE ?>candidate/employment">Employment</a></li>
                <li><a href="<?= URL_BASE ?>candidate/portfolio">Portfolio</a></li>
                <li><a href="<?= URL_BASE ?>candidate/vieweducation">Education</a></li>
                <li><a href="<?= URL_BASE ?>candidate/skills?utm_source=index">Skills</a></li>
                <li><a href="<?= URL_BASE ?>candidate/references">References</a></li>
                <li><a href="<?= URL_BASE ?>candidate/skilltest">Tests</a></li>
                <li><a href="<?= URL_BASE ?>candidate/interest">Interest</a></li>
            </ul>
            <p style="font-size:13px;color:#777">Last signed: <?= date('M d, Y',strtotime($getUserArray["Lastsigned"])) ?></p>
        </div>
        <div class="col-md-9" >
            <div class="page-header" style="margin:0;">
            
                <span class="text-left" style="font-size: 30px;color: #005595;font-weight:bold"><?=$getUserArray["firstname"]." ".$getUserArray["lastname"]?></span>
                <div style="padding-bottom:5px">
                <?php
                    $count=0;
                    foreach($SkillName as $Skills)
                    {
                        $count=$count+1;
                    
                ?>
                <span <?php if ($count==1) echo "class=''"; else echo "class='line-l'";?>  style="font-weight:bold;font-size:14px"><a href="#" style="text-decoration:none;color: #777;"><?=$Skills["SkillName"]?></a></span>
                <?php
                }
                ?>
                </div>
                <span style="padding-right:5px;"><img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span class="line-r"  style="font-weight:bold;font-size:13px"><?=$getUserArray["Country"]?><?php if($getUserArray["Country"]=="") echo "United State"?></span><span style="padding-left:5px;font-size:13px" class=""><?=$getUserArray["Address1"]?><?php if($getUserArray["Address1"]!="") echo ", ";?><?=$getUserArray["State"]?><?php if($getUserArray["State"]!="") echo ", ";?><?=$getUserArray["PostalCode"]?></span><span> <a href="<?= URL_BASE ?>candidate/editoverview" style="text-decoration: none;"><img src="<?=URL_THEMES?>images/btn_edit.png"></a></span> </span>
             </div>
            <div class="">
                <div class="panel-body" style="padding:0">
                    <h4><span style="font-weight:bold">Overview</span></h4>
                        <div class="col-xs-8"  style="padding:0">
                            <span style="padding-right:20px;font-size:12px"><?=nl2br($getCandidates["overview"])?></span>
                            </div>
                        <div class=".col-xs-4" style="float:right;">
                            <img width="230px" src="<?=URL_THEMES.'images/img_YourProfile.jpg';?>">
                            
                        </div>
                        <div class="col-xs-10" style="padding:0;padding-bottom:10px;padding-top:5px;">
                            <div class="col-xs-5" style="padding:0;">
                             <?php
                            if(!empty($getCandidates["video"]))
                            {   
                                
                                $video=URL_MEDIA_VIDEO.$getCandidates["video"];
                               // echo $video;
                                //echo "<video controls autoplay>
                               // <source src='./library/media/video/$video' type='video/mp4'>
                               // </video>";
                              // echo("testt:<pre>");print_r($_SERVER["SERVER_NAME"]);echo("</pre>");
                            ?>
                             <video width="230px" controls autoplay loop>
                                <source src="<?=$video?>">
                             </video>
                           <!--<iframe style="padding:0" id="ytplayer" type="text/html" width="230"  src="http://<?=$_SERVER["SERVER_NAME"].$video?>?autoplay=1&origin=http://example.com" frameborder="0"/></iframe>-->
                            <?php
                            }
                            
                            else{
                            ?>
                                <img width="230px" src="<?=URL_THEMES.'images/img_Youtube.jpg';?>">
                               
                              <?php
                            }
                            ?>
                            </div>
                            <div class="col-xs-4" style="padding:0;">
                                <a href="<?= URL_BASE ?>candidate/upload-video"><img src="<?=URL_THEMES.'images/img_AddVideo.jpg';?>"></a>
                            </div>
                        </div>

                </div>
                <div class="panel-body" style="padding:0">
                    <h4><span style="font-weight:bold">Skills</span></h4>
                    <div class="col-xs-8"  style="padding:0">
                    <?php                   
                    foreach($SkillName as $Skills)
                    {                                           
                    ?>
                        <span style="" class="label-tag pull-left getSkillText"><?= $Skills["SkillName"]?>
                            
                        </span>
                    <?php
                    }?>

                    </div>
                </div>
                <div class="panel-body" style="padding:0">
                    <h4><span style="font-weight:bold">Employment</span><span style="padding-left:10px;"><a href="<?= URL_BASE ?>candidate/employment"><img src="<?=URL_THEMES.'images/btn_AddEmployment.png';?>"></a></span></h4>
                    <div class="col-xs-8"  style="padding:0">
                        <?php
                            foreach($CandidateEmployment as $Employments)
                            {
                        ?>
                        <div style="padding-bottom:10px;">
                            <span style="font-weight:bold"><?=$Employments["CompanyName"]?></span><br>
                            <span style="font-size:13px;"><?=$Employments["PostionHeld"]?></span><br>
                            <span style="font-size:13px;">
                            <?php
                                $StartDate=date('Y',strtotime($Employments["StartDate"]));
                                $EndDate=date('Y',strtotime($Employments["EndDate"]));
                                echo ($StartDate."-".$EndDate)
                               // echo ($EndDate[year]);
                            ?>
                            </span>     
                          </div>               
                              <?php
                            }
                        ?>
                    
                    </div>
                </div>
                <div class="panel-body" style="padding:0">
                    <h4><span style="font-weight:bold">Education</span><span style="padding-left:10px;"><a href="<?= URL_BASE ?>candidate/add-education" style="cursor:pointer"><img src="<?=URL_THEMES.'images/btn_AddEducattion.png';?>"></a></span></h4>
                    <div class="col-xs-8"  style="padding:0">
                        <?php
                            foreach($Education as $values)
                            {
                                if($values["display"]==1){
                        ?>
                        <div style="padding-bottom:10px;">
                            <span style="font-weight:bold"><?=$values["title"]?></span><br>
                            <span style="font-size:13px;"><?=$values["institution_name"]?></span><br>
                            <span style="font-size:13px;">
                            <?php
                                $StartDate=date('Y',strtotime($values["startdate"]));
                                $EndDate=date('Y',strtotime($values["enddate"]));
                                echo ($StartDate."-".$EndDate)
                               // echo ($EndDate[year]);
                            ?>
                            </span>     
                          </div>               
                              <?php
                                }}
                        ?>
                    
                    </div>
                </div>
            </div>
            <div style="padding-top:40px;">
            </div>
        </div>
        
    </div>
</div>
<script>

</script>