<?php
$getUserArray = $this->client;
$getCandidates=$this->getCandidates;
?>
<style>
    ul#nav-left{margin:0;padding:7px 0;margin-bottom: 10px;list-style: none; border-top: 1px solid #bbb;border-bottom: 1px solid #bbb}
    ul#nav-left li{line-height: 35px;}
    ul#nav-left a{color: #777}
    ul#nav-left .active{color: #428bca}

    .page-header {
        border-bottom: 2px solid #d6d6d6;
    }

    .well{
        margin-bottom: 0;
        background-color: #ebebeb;
        border: 1px solid #e3e3e3;
        border-radius: 4px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05) inset;
        margin-bottom: 20px;
        min-height: 20px;
        padding: 19px;
    }

    .logo {
        /*background: url("<?=URL_THEMES?>images/avatar_A.jpg") no-repeat scroll 0 0 rgba(0, 0, 0, 0);*/
        <?php
        $image=URL_MEDIA_PHOTO.$getCandidates["image"];
        ?>
        background: url('<?php if(!empty($getCandidates["image"])) echo  $image; else echo URL_THEMES."images/avatar_none.jpg";?>') no-repeat;
        height: 165px;
        width: 211px;
    }

    .label-tag {
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 3px;
        color: #000;
        margin-bottom: 5px;
        margin-right: 10px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-top: 6px;
        padding-bottom: 6px;
    }

    .pull-left {
        float: left !important;
    }
    }


</style>
<script src="<?=URL_THEMES.'js/pocket.candidate.js?vs=1';?>"></script>
<script>
    var objSkTest = new pocketCandidate();
    var urlImage = '<?=URL_THEMES;?>';
    var ico_expand = urlImage+'images/trees/ico_expand.png';
</script>

<div class="container" style="padding-top:40px;margin-top:0px">
<!--modal-->
    <div class="modal fade" tabindex="-1" role="dialog" id="finish-test" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog modal-sm">
            <div class="modal-content modal-dialog-center">
                <div class="modal-header" style="border-bottom: none">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <div class="modal-title text-center">You have completed the test</div>
                </div>
            </div>
        </div>
    </div>
    <!----end modal-->
    <div class="row">
        <div class="col-md-3">

            <div class="well text-center col-md-12" style="padding:0px"> <?php $image=URL_MEDIA_PHOTO.$getCandidates['image']; ?>
                <div class="" style='height: 165px; width: 211px; background-position: center center; background-image:url("<?=$image?>"); background-repeat: no-repeat;display: inline-block;'>
                </div>
                <div class='col-md-12' style="text-align: right; padding-right:0px"><img style="" src="<?=URL_THEMES?>images/bg_grey_text.png"> </div>
            </div>
            <!-- <div class="text-center" style="padding:0px">
                <div class="logo"><a href="<?= URL_BASE ?>candidate/upload-photo"><img src="<?=URL_THEMES?>images/bg_grey_text.png" style="float:right;padding-top:140px;"></a></div>

            </div>-->
             <a href="#"><?=$getUserArray["emailaddress"]?></a><br/>
            <strong>View my profile</strong> <br/>
            <span>
                <img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span style="font-size:13px;padding-left:5px"><?=$getUserArray["Country"]?><?php if($getUserArray["Country"]=="") echo "United State";?></span><span style="padding-left:5px;font-size:13px" class=""><?=$getUserArray["Address1"]?><?php if($getUserArray["Address1"]!="") echo ", "; ?> <?=$getUserArray["State"]?></span>
            </span>
            <span><strong>Expected Salary: <?=$getCandidates["minimumsalary"]?><?php if($getCandidates["minimumsalary"]!="") echo "-";?><?=$getCandidates["maximumsalary"]?><?php if($getCandidates["maximumsalary"]!="")echo "K";?></strong></span><br/>
            <p style="padding: 10px 0">
                <!--<i class="lbl-log">Edit</i>-->
                 <a href="<?= URL_BASE ?>candidate/editoverview"><img src="<?=URL_THEMES?>images/btn_edit.png"></a>
            </p>
            <ul id="nav-left">
                <li><a href="<?= URL_BASE ?>candidate/profile-builder?utm_source=contact">Profile builder</a></li>
                <li><a href="<?= URL_BASE ?>candidate/profile">Overview</a></li>
                <li><a href="<?= URL_BASE ?>candidate/contact-info">Contact Info</a></li>
				<li> <a href="<?= URL_BASE ?>candidate/employment">Employment</a></li>
                <li><a href="<?= URL_BASE ?>candidate/portfolio">Portfolio</a></li>
                <li><a href="<?= URL_BASE ?>candidate/vieweducation">Education</a></li>
                <li><a href="<?= URL_BASE ?>candidate/skills?utm_source=index">Skills</a></li>
                <li><a href="#">References</a></li>
                <li ><strong><a class="active" href="<?= URL_BASE ?>candidate/skilltest">Tests</a></strong></li>
                <li><a href="<?= URL_BASE ?>candidate/interest">Interest</a></li>
            </ul>
            <p style="font-size:13px;color:#777">Last signed: <?= date('M d, Y',strtotime($getUserArray["Lastsigned"])) ?></p>
        </div>

        <div class="col-md-9">
            <div class="page-header  md-col-12 contain-right" style="margin:0; padding-left: 0px; padding-right: 0px">
                <div class="text-left" style="font-size: 30px;color: #005595;font-weight:bold">Test</div>
                <div class="col-xs-8"  style="padding-left:0;padding-right: 0;padding-top: 25px">
                    <?php
                    $testIDs = $this->listTestID;
                    if(!empty($testIDs)&& count($testIDs)>0){
                        foreach($testIDs as $kk=>$testIDsInfo){?>

                            <span style="cursor: pointer" class="label-tag pull-left" onclick="javascript:objSkTest.skill_Test_View(<?=$testIDsInfo['TestID']?>)"> <?= $testIDsInfo['TestName']?></span>
                     <?php   }
                    }
                    ?>
                </div>
            </div>
           <!--
            <div class="md-col-12 contain-right" style="padding-left: 0px; padding-right: 0px">

            </div> -->

        </div>
    </div>
</div>



