<?php
$getUserArray = $this->client;
$getCandidates=$this->getCandidates;

?>
<style>
    ul#nav-left{margin:0;padding:7px 0;margin-bottom: 10px;list-style: none; border-top: 1px solid #bbb;border-bottom: 1px solid #bbb}
    ul#nav-left li{line-height: 35px;}
    ul#nav-left a{color: #777}
    ul#nav-left .active{color: #428bca}

    .page-header {
        border-bottom: 2px solid #d6d6d6;
    }

    .well{
        margin-bottom: 0;
        background-color: #ebebeb;
        border: 1px solid #e3e3e3;
        border-radius: 4px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05) inset;
        margin-bottom: 20px;
        min-height: 20px;
        padding: 19px;
    }

    .logo {
        /*background: url("<?=URL_THEMES?>images/avatar_A.jpg") no-repeat scroll 0 0 rgba(0, 0, 0, 0);*/
        <?php
        $image=URL_MEDIA_PHOTO.$getCandidates["image"];
        ?>
        background: url('<?php if(!empty($getCandidates["image"])) echo  $image; else echo URL_THEMES."images/avatar_none.jpg";?>') no-repeat;
        height: 165px;
        width: 211px;
    }


    }


</style>
<script src="<?=URL_THEMES.'js/pocket.candidate.js?vs=1';?>"></script>
<script>
    var objSkTest = new pocketCandidate();
    var urlImage = '<?=URL_THEMES;?>';
    var ico_expand = urlImage+'images/trees/ico_expand.png';
</script>

<div class="container" style="padding-top:40px;margin-top:0px">
<!--modal-->
    <div class="modal fade" tabindex="-1" role="dialog" id="finish-test" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog modal-sm">
            <div class="modal-content modal-dialog-center">
                <div class="modal-header" style="border-bottom: none">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <div class="modal-title text-center">You have completed the test</div>
                </div>
            </div>
        </div>
    </div>
    <!----end modal-->
    <div class="row">
        <div class="col-md-3">
            <!--
            <div class="well text-center col-md-12" style="padding:0px">
                <div class="" style='height: 165px; width: 211px; background-position: center center; background-image:url("<?=URL_THEMES?>images/avatar_A.jpg"); background-repeat: no-repeat;display: inline-block;'>
                </div>
                <div class='col-md-12' style="text-align: right; padding-right:0px"><img style="" src="<?=URL_THEMES?>images/bg_grey_text.png"> </div>
            </div>-->
            <div class="text-center" style="padding:0px">
                <div class="logo"><a href="<?= URL_BASE ?>candidate/upload-photo"><img src="<?=URL_THEMES?>images/bg_grey_text.png" style="float:right;padding-top:140px;"></a></div>

            </div>
            <a href="#"><?=$getUserArray["emailaddress"]?></a><br/>
            <strong>View my profile</strong> <br/>
            <span>
                <img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span style="font-size:13px;padding-left:5px"><?=$getUserArray["Country"]?><?php if($getUserArray["Country"]=="") echo "United State";?></span><span style="padding-left:5px;font-size:13px" class=""><?=$getUserArray["Address1"]?><?php if($getUserArray["Address1"]!="") echo ", "; ?> <?=$getUserArray["State"]?></span>
            </span>
            <span><strong>Expected Salary: <?=$getCandidates["minimumsalary"]?><?php if($getCandidates["minimumsalary"]!="") echo "-";?><?=$getCandidates["maximumsalary"]?><?php if($getCandidates["maximumsalary"]!="")echo "K";?></strong></span><br/>
            <p style="padding: 10px 0">
                <!--<i class="lbl-log">Edit</i>-->
                 <a href="<?= URL_BASE ?>candidate/editoverview"><img src="<?=URL_THEMES?>images/btn_edit.png"></a>
            </p>
            <ul id="nav-left">
                <li><a href="<?= URL_BASE ?>candidate/profile-builder?utm_source=contact">Profile builder</a></li>
                <li><a href="<?= URL_BASE ?>candidate/profile">Overview</a></li>
                <li><a href="<?= URL_BASE ?>candidate/contact-info">Contact Info</a></li>
				<li> <a href="<?= URL_BASE ?>candidate/employment">Employment</a></li>
                <li><a href="<?= URL_BASE ?>candidate/portfolio">Portfolio</a></li>
                <li><a href="<?= URL_BASE ?>candidate/vieweducation">Education</a></li>
                <li><a href="<?= URL_BASE ?>candidate/skills?utm_source=index">Skills</a></li>
                <li><a href="#">References</a></li>
                <li ><strong><a class="active" href="<?= URL_BASE ?>candidate/skilltest">Tests</a></strong></li>
                <li><a href="#">Interest</a></li>
            </ul>
            <p style="font-size:13px;color:#777">Last signed: <?= date('M d, Y',strtotime($getUserArray["Lastsigned"])) ?></p>
        </div>

        <div class="col-md-9">
            <?php
            $testIDs = $this->listTestID;
            if(count($testIDs) >1 && !empty($testIDs)){?>
                    <!---->
                    <div class="modal fade" tabindex="-1" id="Select-a-Required-Test" role="dialog" data-keyboard="false" data-backdrop="static">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content modal-dialog-center">
                                <div class="modal-header">
                                    <button type="button" class="close close-modal" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h2 class="modal-title" style="font-size: 20px">Select a Required Test</h2>
                                </div>
                                <div class="modal-body login-modal">
                                    <div class="col-md-12">
                                        <div >
                                            <select name="testID" id="testID_testID" class="form-control">
                                                <option value="">Select a Required Test</option>
                                                <?php
                                                foreach($testIDs as $k1=>$testIDsInfo){
                                                    ?>
                                                    <option value="<?=$testIDsInfo['TestID']?>"><?=$testIDsInfo['TestName']?></option>
                                                <?php
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <button style="background-color:#fff; border:#fff">&nbsp;</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!---->

<script type="text/javascript">
                    $('#Select-a-Required-Test').modal('show');
                    $("#testID_testID").unbind("change").bind("change",function(){
                        var testID = "";
                        testID = $("#testID_testID option:selected").val();
                        //testName = $("#testID_testID option:selected").text();
                        if(testID !=""){
                            $('#Select-a-Required-Test').modal('hide');
                           // $("#select_require_test").css({"font-size": "30px","color": "#005595","font-weight":"bold"});
                            //$("#select_require_test").text(testName);
                            objSkTest.skill_Test_View(testID);
                        }

                    });

                    $(".close-modal").unbind("click").bind("click",function(){
                        $(".header-header").show();
                    });

                </script>
                <div class="page-header header-header" style="margin:0; display: none">
                    <span class="text-left" style="font-size: 30px;color: #005595;font-weight:bold">NO TEST IS SELECTED</span>
                </div>

            <?php } else if(count($testIDs) == 1){
            foreach ($testIDs as $k1=>$testIDsInfo){
                $testID = $testIDsInfo['TestID'];
            }
            ?>
                <script type="text/javascript">
                    var testID = "";
                    testID ='<?=$testID?>' ;
                    $(document).ready(function(){
                        objSkTest.skill_Test_View(testID);
    })
</script>
           <?php } else{ ?>
                <div class="page-header" style="margin:0;">
                    <span class="text-left" style="font-size: 30px;color: #005595;font-weight:bold">NO TEST IS REQUIRED</span>
                </div>
           <?php }
            ?>

            <div class="md-col-12 contain-right" style="padding-left: 0px; padding-right: 0px">

            </div>

        </div>
    </div>
</div>



