<div class="container" >
    <div class="page-header">
        <h1>
            <span class="text-left" style="color: #2a6496">Watchlist</span>
        </h1>
    </div>
    <div class="" style="height: 40px;background-color: #2a6496">

    </div>
    <div class="table-responsive">

        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>
                    <span><input type="checkbox" name=""/> <strong>Career Create</strong></span>
                </th>
                <th><strong>Company Name</strong></th>
                <th>Career Title</th>
                <th>Career Description</th>
                <th>Apply Date</th>
                <th>Action<span class="caret"></span></th>
            </tr>
            </thead>
            <tbody>
            <tr class="warning">
                <td><span><input type="checkbox" name=""/> <strong>5/16/14</strong></span> <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span></td>
                <td><a href="#" style="text-decoration: underline; color: #777">Apple Inc</a></td>
                <td style="color: #777">Experienced Atlatasian Administrator</td>
                <td style="color: #777">Experienced Atlatasian Administrator   </td>
                <td><strong>26 May 2014</strong></td>
                <td>
                    <i style="color: #eea236" class="glyphicon glyphicon-star"></i> &nbsp;
                    <i style="color: #bbb"  class="glyphicon glyphicon-remove"></i>
                </td>
            </tr>
            <tr class="warning">
                <td><span><input type="checkbox" name=""/> <strong>5/16/14</strong></span> <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span></td>
                <td><a href="#" style="text-decoration: underline; color: #777">Apple Inc</a></td>
                <td style="color: #777">Experienced Atlatasian Administrator</td>
                <td style="color: #777">Experienced Atlatasian Administrator   </td>
                <td><strong>26 May 2014</strong></td>
                <td>
                    <i style="color: #eea236" class="glyphicon glyphicon-star"></i> &nbsp;
                    <i style="color: #bbb"  class="glyphicon glyphicon-remove"></i>
                </td>
            </tr><tr class="warning">
                <td><span><input type="checkbox" name=""/> <strong>5/16/14</strong></span> <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span></td>
                <td><a href="#" style="text-decoration: underline; color: #777">Apple Inc</a></td>
                <td style="color: #777">Experienced Atlatasian Administrator</td>
                <td style="color: #777">Experienced Atlatasian Administrator   </td>
                <td><strong>26 May 2014</strong></td>
                <td>
                    <i style="color: #eea236" class="glyphicon glyphicon-star"></i> &nbsp;
                    <i style="color: #bbb"  class="glyphicon glyphicon-remove"></i>
                </td>
            </tr><tr class="warning">
                <td><span><input type="checkbox" name=""/> <strong>5/16/14</strong></span> <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span></td>
                <td><a href="#" style="text-decoration: underline; color: #777">Apple Inc</a></td>
                <td style="color: #777">Experienced Atlatasian Administrator</td>
                <td style="color: #777">Experienced Atlatasian Administrator   </td>
                <td><strong>26 May 2014</strong></td>
                <td>
                    <i style="color: #eea236" class="glyphicon glyphicon-star"></i> &nbsp;
                    <i style="color: #bbb"  class="glyphicon glyphicon-remove"></i>
                </td>
            </tr>
            <tr class="warning">
                <td><span><input type="checkbox" name=""/> <strong>5/16/14</strong></span> <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span></td>
                <td><a href="#" style="text-decoration: underline; color: #777">Apple Inc</a></td>
                <td style="color: #777">Experienced Atlatasian Administrator</td>
                <td style="color: #777">Experienced Atlatasian Administrator   </td>
                <td><strong>26 May 2014</strong></td>
                <td>
                    <i style="color: #eea236" class="glyphicon glyphicon-star"></i> &nbsp;
                    <i style="color: #bbb"  class="glyphicon glyphicon-remove"></i>
                </td>
            </tr>
            <tr class="warning">
                <td><span><input type="checkbox" name=""/> <strong>5/16/14</strong></span> <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span></td>
                <td><a href="#" style="text-decoration: underline; color: #777">Apple Inc</a></td>
                <td style="color: #777">Experienced Atlatasian Administrator</td>
                <td style="color: #777">Experienced Atlatasian Administrator   </td>
                <td><strong>26 May 2014</strong></td>
                <td>
                    <i style="color: #eea236" class="glyphicon glyphicon-star"></i> &nbsp;
                    <i style="color: #bbb"  class="glyphicon glyphicon-remove"></i>
                </td>
            </tr>
            <tr class="warning">
                <td><span><input type="checkbox" name=""/> <strong>5/16/14</strong></span> <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span></td>
                <td><a href="#" style="text-decoration: underline; color: #777">Apple Inc</a></td>
                <td style="color: #777">Experienced Atlatasian Administrator</td>
                <td style="color: #777">Experienced Atlatasian Administrator   </td>
                <td><strong>26 May 2014</strong></td>
                <td>
                    <i style="color: #eea236" class="glyphicon glyphicon-star"></i> &nbsp;
                    <i style="color: #bbb"  class="glyphicon glyphicon-remove"></i>
                </td>
            </tr>
            <tr class="warning">
                <td><span><input type="checkbox" name=""/> <strong>5/16/14</strong></span> <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span></td>
                <td><a href="#" style="text-decoration: underline; color: #777">Apple Inc</a></td>
                <td style="color: #777">Experienced Atlatasian Administrator</td>
                <td style="color: #777">Experienced Atlatasian Administrator   </td>
                <td><strong>26 May 2014</strong></td>
                <td>
                    <i style="color: #eea236" class="glyphicon glyphicon-star"></i> &nbsp;
                    <i style="color: #bbb"  class="glyphicon glyphicon-remove"></i>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="" style="height: 40px;background-color: #333">

        </div>
    </div>

</div>
<script>

</script>