<script src="<?=URL_THEMES.'js/pocket.candidate.js';?>"> </script>
<script>
    var objPK = new pocketCandidate();
    $(".navbar-nav li").removeClass("active");//this will remove the active class from previously active menu item
</script>

<div class="container" >
    <div class="">
        <h1 style="height:60px; padding-top:10px">
            <span class="text-left" style="color: #2a6496">Watchlist</span>
        </h1>
    </div>
    <div class="" style="height: 40px;background-color: #2a6496">

    </div>
    <div class="table-responsive" style="font-size:12px">

        <table style="margin-bottom:0;"  class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th style="width:160px">
                    <span><input type="checkbox" id="ckAll" name=""/> <strong>Opportunity Create</strong></span>
                </th>
                <th style="width:150px"><strong>Company Name</strong></th>
                <th style="width:175px">Opportunity Title</th>
                <th>Opportunity Description</th>
                <th style="width:130px">Apply Date</th>
                <th style="width:80px">Action<span ></span></th>
            </tr>
            </thead>
            <tbody>
            <?php
            $wlist = $this->wlist;
            if($wlist !=""){
                foreach($wlist as $k=>$wlistInfo){ ?>
                    <tr class="warning trIsck">
                        <td><span><input type="checkbox" class="isck" name=""/> <strong><?=$wlistInfo['posteddate']?></strong></span> <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span></td>
                        <td><a href="#" style="text-decoration: underline; color: #777"><?=$wlistInfo['Companyname']?></a></td>
                        <td style="color: #777"><?=$wlistInfo['title']?></td>
                        <td style="color: #777"><?=$wlistInfo['careerdescription']?>  </td>
                        <td><strong><?=$wlistInfo['CandidateApplyDate']?></strong></td>
                        <td>
                            <span class="glyphicon glyphicon-star" style="padding-left:15px;color:#f7ce12"></span>&nbsp;
                            <img onclick="javascript:objPK.deleteWatchList(<?=$wlistInfo['OpportunityID']?>)" src="<?=URL_THEMES?>images/ico_del.png?>" style="height:13px; width:13px; margin-top:-5px; cursor: pointer">
                        </td>
                    </tr>

              <?php  }
            }
            ?>

            </tbody>
        </table>
        <div class="" style="height: 40px;background-color: #333"> </div>
    </div>

</div>

<script>
    $('#ckAll').unbind('click').bind('click',objPK.watchListCheckedAll);
    $('.isck').unbind('click').bind('click',objPK.watchListIsChecked);
</script>

