<script src="<?=URL_THEMES.'js/register.js';?>"></script>
<style>
.has-error .form-control {
    border-color: #a94442;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
}
#Register .message{color: #b81900;}
</style>
<div class="header" style="background-color: #333;padding: 10px 0; color: #fff;">
    <div class="container">
        <small>This is the resume of the future! With Pocket Recruiter, </small><br/>
       <b> You'll not only get the hiring manager's attention-you'll keep it</b>
    </div>
</div>
<div class="container" >
<div class="page-header" style="margin:0;">
    <h1>
        <span class="text-left" style="font-size: 25px;color: #2a6496">Create a Pocket Recruiter Account</span>
        <span class="text-right pull-right" style="font-size: 14px;position: relative;top: 20px">Already have a Pocket Recruiter account? <span class="lbl-log">Sign in</span> <span class="lbl-log">Register</span></span>

    </h1>
</div>

<div class="col-md-8"  style="padding:0">
    <div class="col-md-7" style="margin:0;padding:0">
  
        <form role="form" method="post" name="Register" id="Register" action="<?= URL_BASE . 'register/do-register' ?>">
            <div class="form-group ">
                <label for="email">Email address</label>
              <div class="form-group">
              
                <input name="emailaddress" type="email" class="form-control" id="emailaddress" placeholder="Enter email">
                <span class="message" id="Email1_message"></span>
              </div>
            </div>
            <div class="form-group">
                <label for="credential">First Name</label>
              <div class="form-group">
                <input type="text" class="form-control" id="firstname" name="firstname" placeholder="Enter First Name" >
                <span class="message" id="FirstName_message"></span>
              </div>
            </div>
            <div class="form-group">
                <label for="email">Last Name</label>
              <div class="form-group">
                <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Enter Last Name" >
                 <span class="message" id="LastName_message"></span>
              </div>
            </div>
            <div class="form-group">
                <label for="email">User Name</label>
              <div class="form-group">
                <input type="text" class="form-control" id="loginname" name="loginname" placeholder="Enter User Name" >
                 <span class="message" id="loginname_message"></span>
              </div>
            </div>
            
            <div class="form-group">
                <label for="credential">Password</label>
              <div class="form-group">
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password"  >
                 <span class="message" id="Password_message"></span>
              </div>
                
            </div>
             <div class="form-group">
                <label for="credential">Retype Password</label>
                <div class="form-group">
                <input type="password" class="form-control" id="RetypePassword" name="RetypePassword">
                 <span class="message" id="RetypePassword_message"></span>
              </div>
                
            </div>
            <div class="form-group">
                <label for="credential">Account type</label>
                <br><span style="font-size:12px;"> How dou you want to represent yourse to Employ on cardcabe?</span></br>
                
                <label class="radio-inline">
                
                                   <input type="radio" name="usertype" id="usertype" value="2" checked=""><span style="font-size:12px;"> Cardcabe</span>
                </label>
                <label class="radio-inline">
                  <input type="radio" name="usertype" id="usertype" value="1"><span style="font-size:12px;"> Company</span>
                </label>
                
                
            </div>
                            <?php
                //$source = new PR_Api_Register();
                $source= new PR_Api_Core_Register();

$sourceOptions = $source->getAboutUsList_forRegisterPage();
$SourceHtml = "<select class=\"form-control\" id=\"About_us\" name=\"About_us\"><option value=\"\">Select </option>";
foreach ($sourceOptions as $code) {
    $selected = '';
    
    $SourceHtml .= "<option value=\"$code\" $selected>$code</option>";
}
$SourceHtml .="</select>"; 
                ?>
            <div class="form-group">
                <label for="credential">How did you hear about us?</label><br>
               <div class="form-group">
                <?= $SourceHtml;?>
                 <span class="message" id="About_us_message"></span>
              </div>
                <div class="form-group">
                <input type="checkbox" name="accept" id="accept" class="" > I have read and accept the terms of Service
<br><span class="message" id="accept_message"></span>
              </div>
                
                
            </div>
            
            <button class="btn btn-primary" type="button" id="cmd-register">Register</button>
        </form>
    </div>
    <div class="col-md-6">
    </div>

</div>
<div class="col-md-4" style="padding:0;border-left: 1px solid #ddd; height: 400px;">
    <div style="height: 50px; ">
        <p style="float:left;width: 20%;color: #fff;background-color: #4cae4c;padding: 15px 0; text-align: center"><i class="glyphicon glyphicon-lock"></i></p>
        <p style="float:left;width: 80%;color: #fff;background-color: #333;padding: 5px 0; text-align: center">
            We value your privacy<br/> <small>Privacy Policy</small>
        </p>
    </div>
    <div class="col-lg-12">
       <h3><span class="text-left" style="color: #2a6496;padding-right: 20px;"><i class="glyphicon glyphicon-ok"></i></span><span class="text-center" >Pocket Recruiter</span></h3>
        <p><smal>
            At a bare minimum, the front controller needs one or more paths to directories containing action controllers in order to do its work. A variety of methods may also be invoked to further tailor the front controller environment and that of its helper classes.</smal>
        </p>
        <p><span class="lbl-log">Register</span></p>
    </div>
</div>
</div>
