<div class="header" style="background-color: #333;padding: 10px 0; color: #fff;">
    <div class="container">
        <small>This is the resume of the future! With Pocket Recruiter, </small><br/>
       <b> You'll not only get the hiring manager's attention-you'll keep it</b>
    </div>
</div>
<div class="container" >
<div class="page-header" style="margin:0;">
    <h1>
        <span class="text-left" style="font-size: 25px;color: #2a6496">Create a Pocket Recruiter Account</span>
        <span class="text-right pull-right" style="font-size: 14px;position: relative;top: 20px">Already have a Pocket Recruiter account? <span class="lbl-log">Sign in</span> <span class="lbl-log">Register</span></span>

    </h1>
</div>
<div class="col-md-8"  style="padding:0">
    <div class="col-md-7" style="margin:0;padding:0">
        <form role="form">
            <div class="form-group ">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" >
            </div>
            <div class="form-group">
                <label for="email">First Name</label>
                <input type="text" class="form-control" id="firstname" >
            </div>
            <div class="form-group">
                <label for="email">Last Name</label>
                <input type="text" class="form-control" id="lastname" >
            </div>
            <div class="form-group">
                <label for="credential">Password</label>
                <input type="password" class="form-control" id="credential" >
                
            </div>
             <div class="form-group">
                <label for="credential">Retype Password</label>
                <input type="password" class="form-control" id="credential">
                
            </div>
            <div class="form-group">
                <label for="credential">Account type</label>
                <br><span style="font-size:12px;"> How dou you want to represent yourse to Employ on cardcabe?</span></br>
                <label class="radio-inline">
                  <input type="radio" name="inlineRadioOptions" id="Cardcabe" value="option1"><span style="font-size:12px;"> Cardcabe</span>
                </label>
                <label class="radio-inline">
                  <input type="radio" name="inlineRadioOptions" id="Company" value="option2"><span style="font-size:12px;"> Company</span>
                </label>
                
                
            </div>
            <div class="form-group">
                <label for="credential">How did you hear about us?</label><br>
                <select class="form-control">
                  <option>Select</option>
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                  <option>5</option>
                </select>
                
                <br><input type="checkbox"><span style="font-size:12px;"> I have read and accept the terms of Service</span>

                
                
            </div>
            
            <button class="btn btn-primary" type="button">Register</button>
        </form>
    </div>
    <div class="col-md-6">
    </div>

</div>
<div class="col-md-4" style="padding:0;border-left: 1px solid #ddd; height: 400px;">
    <div style="height: 50px; ">
        <p style="float:left;width: 20%;color: #fff;background-color: #4cae4c;padding: 15px 0; text-align: center"><i class="glyphicon glyphicon-lock"></i></p>
        <p style="float:left;width: 80%;color: #fff;background-color: #333;padding: 5px 0; text-align: center">
            We value your privacy<br/> <small>Privacy Policy</small>
        </p>
    </div>
    <div class="col-lg-12">
       <h3><span class="text-left" style="color: #2a6496;padding-right: 20px;"><i class="glyphicon glyphicon-ok"></i></span><span class="text-center" >Pocket Recruiter</span></h3>
        <p><smal>
            At a bare minimum, the front controller needs one or more paths to directories containing action controllers in order to do its work. A variety of methods may also be invoked to further tailor the front controller environment and that of its helper classes.</smal>
        </p>
        <p><span class="lbl-log">Register</span></p>
    </div>
</div>
</div>