<style>
body {
    background: none repeat scroll 0 0 #ededed;
}
.has-error .form-control1 {
    border-color: #a94442;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
}

#profile .message{padding-top: 3px; font-style: italic;color: #b81900;font-size:12px;}

 .redborder{
        border:#F00 solid 1px;
        background-color:yellow;
      }
      .greenborder  {
        border:#0F3 solid 1px;
        background-color:#6F6;
      }
       .message{padding-top: 3px; font-style: italic;color: #b81900;font-size:12px;}
</style>



  
  <script type="text/javascript">
    $(document).ready(function()
    {
         
    });
  </script>

<?php


?>
<!--<header class="subhead" id="overview">-->
 


<div class="container" >       
            
<div class="page-header" style="margin:0;">
    <h3>
        <span class="text-left" style="font-size: 25px;color: #2a6496;font-weight:bold"> Add Company</span>
        

    </h3>
</div>
    <div class="col-md-8"  style="background:#ffffff;margin-top:15px;margin-botton:50px;border-radius: 10px;">
          
      <div class="col-md-6"  style="padding:0">     

      <form enctype="multipart/form-data"   method="POST" name="profile" id="profile"  action="<?= URL_BASE . 'companyprofile/do-add-company'?>" role="form">
      
     
             <div class="form-group">
                <label for="credential">Company Name</label>
              <div class="form-group">
              <input type="hidden" class="form-control" id="CompanyID" name="CompanyID">
                <input type="text" class="form-control" id="Companyname" name="Companyname"  >
                <span class="message" id=""></span>
              </div>
            </div>
            <div class="form-group">
                <label for="email">Industry</label>
              <div class="form-group">
                <input type="text" class="form-control" id="Industry" name="Industry"  >
                 <span class="message" id=""></span>
              </div>
            </div>
            <div class="form-group ">
                <label >Address</label>
              <div class="form-group">
              
                <input name="Address"  class="form-control" id="Address" >
               
              </div>
            </div>
           
            <div class="form-group">
                <label >Country</label>
              <div class="form-group">
                <input type="text" class="form-control" id="country" name="country"  >
                 <span class="message" id=""></span>
              </div>
            </div>
            
            <div class="form-group">
                <label for="credential">Phone</label>
              <div class="form-group">
                <input type="text" class="form-control" id="PhoneNumber" name="PhoneNumber"  >
                 <span class="message" id="PhoneNumber_message"></span>
              </div>
                
            </div>
             <div class="form-group">
                <label for="credential">Email Info</label>
                <div class="form-group">
                <input type="text" class="form-control" id="emailinfo" name="emailinfo" >
                 <span class="message" id="Email1_message"></span>
              </div>
                
            </div>
            <div class="form-group">
                <label for="credential">Zip Code</label>
                <div class="form-group">
                <input type="text" class="form-control" id="Zipcode" name="Zipcode" >
                 <span class="message" id=""></span>
              </div>
                
            </div>
            <div class="form-group">
                <label for="credential">Logo</label>
                <br><input type="file"  size="30"   name="images" id="images">                               
            </div>
            <!-- -->
            <div class="form-group">
                <label for="credential">Decription</label>
                <div class="form-group">
                
                <textarea class="form-control" rows="3" name="Description" id="Description">
                    
                </textarea>
                 <span class="message" id=""></span>
              </div>
                
            </div>
             
           <div class="">
           
                    
                        <button type="submit" class="btn btn-success" id="">
                            <strong>Save</strong>
                        </button>

                    
           </div>
                        
        </form>
       
            <div style="padding-top:20px;">
            </div>
        </div>
    </div>
</div>
<div style="padding-top:40px;">
</div>

<!--</header>-->
<!-- jQuery Version 1.11.0 -->

<script type="text/javascript">
 $(document).ready(function () {
  $("ul.nav li#dasboard-test").removeClass("active");
     var error = false; 
         $('#emailinfo').blur(function () {
         
         if($('#emailinfo').val()!=='')
         {
            
            var x = $('#emailinfo').val();
            var atpos = x.indexOf("@");
            var dotpos = x.lastIndexOf(".");
            
            if(atpos<1 || dotpos<atpos+2 || dotpos+2>=x.length){
                error = true;
                $("#Email1_message").addClass('has-error');
                $("#Email1_message").html("Email info is not a valid email address");
                }else{
                $("#Email1_message").removeClass('has-error').addClass('has-success');
                $("#Email1_message").html('');
            }  
         }
             
             
        });
        //
       $('#PhoneNumber').blur(function () {
            //var error = false; 
            var phone=$('#PhoneNumber').val();
            var phoneno = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/; 
            if (!phone.match(phoneno) && phone.length >1) {
                error = true;
                $('#PhoneNumber_message').addClass('has-error');
                $("#PhoneNumber_message").html("Phone Number must be a valid 10 digit number with optional extension similar to XXX XXX XXXX ");
                
            }else{
                            
               $("#PhoneNumber_message").removeClass('has-error').addClass('has-success');
                $("#PhoneNumber_message").html('');
            }
        });
         $( "#profile" ).submit(function( event ) {
                //alert( "Handler for .submit() called." );
                //event.preventDefault();
                if($('#emailinfo').val()!=='')
                 {
                    var x = $('#emailinfo').val();
                    var atpos = x.indexOf("@");
                    var dotpos = x.lastIndexOf(".");
                    
                    if(atpos<1 || dotpos<atpos+2 || dotpos+2>=x.length){
                        error = true;
                        $("#Email1_message").addClass('has-error');
                        $("#Email1_message").html("Email info is not a valid email address");
                        event.preventDefault();
                        }else{
                        $("#Email1_message").removeClass('has-error').addClass('has-success');
                        $("#Email1_message").html('');
                    }  
                 }
                 var phone=$('#PhoneNumber').val();
            var phoneno = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/; 
            if (!phone.match(phoneno) && phone.length >1) {
                error = true;
                $('#PhoneNumber_message').addClass('has-error');
                $("#PhoneNumber_message").html("Phone Number must be a valid 10 digit number with optional extension similar                  to XXX XXX XXXX ");
                event.preventDefault();
                
            }else{
                            
               $("#PhoneNumber_message").removeClass('has-error').addClass('has-success');
                $("#PhoneNumber_message").html('');
            }
               
});
 });
</script>



