<?php
    $company=$this->company;
   // print_r($company);
?>

<div class="container" >  
    <div class="col-xs-2" style="padding-top:20px;">
    <?php
    if($company["images"]!="")
    {
    ?>
        <img width="150px" src="<?=URL_MEDIA_COMPANY_PROFILE.$company["images"]?>">
    <?php
    }else
    {
    ?>
    <img width="150px" src="<?=URL_THEMES?>images/none.png">
    <?php
    }?>
        <br><span class="text-left" style="font-size: 14px;color: #2a6496;"><?= $company["Companyname"]?></span>
        
    </div>     
   <div class="col-xs-9">         
    <div class="page-header" style="margin:0;">
        <h3>       <?php 
      //  print_r($company);  
        ?>
        
            <span class="text-left" style="font-size: 25px;color: #2a6496;font-weight:bold"><?= $company["Companyname"]?></span>         
            <br><spanclass="text-left" style="font-size:14px;font-weight:normal"><?= $company["Industry"]?> company</span>
            <span style="padding-left:440px;"> <a href="<?= URL_BASE ?>companyprofile/editprofile?companyid=<?= $company["CompanyID"] ?>"><button class="btn btn-success" type="button" >Edit Profile</button></a></span> 
			<!--<span style="padding-left:440px;"> <a href="<?= URL_BASE ?>companyprofile/upload?companyid=<?= $company["CompanyID"] ?>&pageajax=upload"><button class="btn btn-success" type="button" >Edit Profile</button></a></span> -->
</h3>
        
        <span style="font-weight:bold;"><?=$company["country"]?></span><i><span style="padding-left:15px">Address:<?=$company["Address"]?></span><span style="padding-left:0px;"></span><span style="padding-left:15px;">Mail info:<?=$company["emailinfo"]?></span></i>
    </div>
     <div class="col-xs-12" >
        <h4><span style="font-weight:bold">Overview</span></h4>
        <div class="col-xs-8"  style="padding:0">
        <span style="padding-right:20px;"><?=nl2br($company["Decreption"])?></span>
        </div>
        <div class=".col-xs-4">
            <img width="200px" src="<?=URL_THEMES.'images/video.PNG';?>">
			
		</div>
        
     </div>
     <div class="col-xs-9" >
            <h4><span style="font-weight:bold">Other Companies In This Industry</span></h4>
            <div class="col-xs-3">
                <span>test company</span><br>
                <span>test company</span><br>
                <span>test company</span><br>
            </div>
            <div class="col-xs-3">
                <span>test company</span><br>
                <span>test company</span><br>
                <span>test company</span><br>
            </div>
            <div class="col-xs-3">
                <span>test company</span><br>
                <span>test company</span><br>
                <span>test company</span><br>
            </div>
     </div>
    </div>
     
     
</div>

<!--</header>-->
<!-- jQuery Version 1.11.0 -->

<script src="<?=URL_THEMES.'js/profile.js';?>"></script>

<script type="text/javascript">
 
</script>
