<?php
    $company=$this->company;
	$listOrtherCompany=$this->listOrtherCompany;
    $stateInfo = $this->stateOfCompany;
   //echo ("<br><br><pre>");print_r($company);echo("</pre>");
?>
<style>
    body {
    background: none repeat scroll 0 0 #ededed;
    
}
.text-left{
    padding-top: 10px;
}.line-r{
    border-right: 1px solid #d6d6d6;
    padding-right: 10px;
    height: 10px;
    
}

.page-header {
    border-bottom: 2px solid #d6d6d6;
}
.logo{
       /* background: url('<?=URL_THEMES?>images/avatar_none.jpg') no-repeat ;*/
       <?php
        $image=URL_MEDIA_COMPANY_PROFILE.$company["images"];
       ?>
       background: url('<?php if(!empty($company["images"])) echo  $image; else echo URL_THEMES."images/none.png";?>') no-repeat;
	   background-size: 100% 100%;
        width: 211px;
        height: 105px;
    }
ul#nav-left {
    border-bottom: 2px solid #bbb;
    border-top: 2px solid #bbb;}
	
</style>


<div class="container" style="padding-top:40px;">

    <div class="row">
     <div class="col-md-3">
        <div class="text-center">
          <div class="logo"></div>

            </div>
            <div  style="font-size: 12px;color: #005595;margin-top:5px"><?=$company["emailinfo"]?></div>
            
            <ul id="nav-left" style="padding-left:0;margin-top:5px">
                <span ><strong style="font-size:13px">Culture Fits</strong></span>
            </ul>
             <div id="nav-left1">
               <img src="<?=URL_THEMES?>images/img_Abc_1.jpg" width="200px;">
            </div>
           <br><br>
        </div>
        <div class="col-md-9" >
            <div class="page-header" style="margin:0;">
            
                <span class="text-left" style="font-size: 30px;color: #005595;font-weight:bold"><?= $company["Companyname"]?></span>
                <div style="padding-bottom:5px">
					<?= $company["Industry"]?> Company
                </div>
                 <span style="padding-right:5px;"><img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span class="line-r"  style="font-weight:bold;font-size:13px"><?php if(!empty($company["country"])) echo $company["country"]; else echo "United States";?></span>
                <span style="padding-left:5px;font-size:13px" class="line-r">
                    <?=$company["Address"]?><?php if(!empty($company["Address2"])) echo ","?> <?=$company["Address2"]?><?php if(!empty($company["city"])) echo ","?> <?=$company["city"]?><?php if(!empty($stateInfo)) echo ","?> <?=$stateInfo?><?php if(!empty($company["Zipcode"])) echo ","?> <?=$company["Zipcode"]?>
                </span>
                <span style="padding-left:5px;font-size:13px" class="line-r"><b>Phone: </b><?=$company["PhoneNumber"]?></span>
                <span style="padding-left:5px;phone-size:13px" ><b>Fax: </b><?=$company["faxnumber"]?>
                    <span> <a href="<?= URL_BASE ?>companyprofile/editprofile?companyid=<?= $company["CompanyID"] ?>" style="text-decoration: none;"><i class="lbl-log">Edit</i></a></span>
                </span>
             </div>
            <div class="">
                <div class="panel-body" style="padding:0">
                    
                        <div class="col-xs-12"  style="padding:0;font-size:12px" id="limitedTextSpace" >
                           <h4><span style="font-weight:bold">Overview</span></h4>
							<div class="col-xs-8"  style="padding:0">
							<span style="padding-right:20px;font-size:12px"><?=nl2br($company["Description"])?></span>
							</div>
							<div class=".col-xs-4" style="float:right;">
								<!--<img width="230px" src="<?=URL_THEMES.'images/video.png';?>">-->
								  <?php
                            if(!empty($company["video"]))
                            {   
                                
                                $video=URL_MEDIA_VIDEO.$company["video"];
                               
                            ?>
                             <video width="230px" controls autoplay loop>
                                <source src="<?=$video?>">
                             </video>
                           <!--<iframe style="padding:0" id="ytplayer" type="text/html" width="230"  src="http://<?=$_SERVER["SERVER_NAME"].$video?>?autoplay=1&origin=http://example.com" frameborder="0"/></iframe>-->
                            <?php
                            }
                            
                            else{
                            ?>
                                <img width="230px" src="<?=URL_THEMES.'images/video.png';?>">
                               
                              <?php
                            }
                            ?>
								<div style="text-align:center"><a href="<?= URL_BASE ?>companyprofile/upload-video?companyid=<?= $company["CompanyID"] ?>">Upload Video</a></div>
								
								
							</div>

           
                         </div>                          
                        </div>
                        
                        <div class="col-xs-12" style="padding:0;padding-bottom:10px;padding-top:15px;">
                           <header class="subhead" id="overview">
							<div class="panel panel-primary" style="border:0;margin-bottom: 0px">
									<div class="panel-heading" style="background-color: #2a6496">
										<h3 class="panel-title">
											<strong>Open career opportunities</strong>
										</h3>
									</div>

								</div>
							</header>
							<div class="tab-content">
								<!-- career list-->
								<div class="tab-pane active" >
								   <!-- <table class="table table-striped  table-stripedgray table-bordered" cellspacing="0" width="100%" style="border-top-color: #eeeeee;font-size:12px;">-->
								   <table id="notificationCk"  style="background-color: #fff" class="table  table-bordered" cellspacing="0" width="100%" style="border-top-color: #eeeeee">
									
										<thead>
										<tr role="row" style="background-color: #eeeeee">
											<th style="width:30%">
												<label>
												 <strong>Job Title</strong>
												</label>
											</th>
											<th style="width:40%">
													<label>
														 <strong>Location</strong>
													</label>
											</th>
											<th style="width:17%">
													<label>
														<strong>Date</strong>
													</label>
											</th>
											<th style="width:13%">
													<label>
														 <strong>States</strong>
													</label>
											</th>
										   
										   
										</tr>
										</thead>
										<tbody>
									  <?php
									  $getListOpp=$this->getListOpp;
									 // echo ("getListOpp:<pre>");print_r($getListOpp);echo("</pre>");
									  foreach($getListOpp as $k=>$values)
									  {
									  ?>
												<tr role="row" class="odd">
													<td>
														<b><?= $values["title"]?></b>
													</td>
													<td><?= $values["location"]." ".$values["zipcode"]?></td>
													<td><?=$values["posteddate"]?></td>
													<td><img src="<?=URL_THEMES.'images/btn_apply.png';?>"></td>
													
													
												</tr>

									  <?php
									  }
									  ?>

										</tbody>
									</table>


								</div>
								<!--career list end-->
							 
						 </div>
						 </div>
                        </div>
						<?php
							if(!empty($listOrtherCompany)){
						?>
						<div class="col-xs-12"; style="padding-left:0" >
							<h4 style="fornt-size:16px"><span style="font-weight:bold;" >Other Companies In This Industry</span></h4>
						<?php
							
							foreach($listOrtherCompany as $companys){
								if($companys["CompanyID"]!=$company["CompanyID"]){
							
						?>
				
					<div class="col-xs-3" style="padding-left:0">
						<a href="#" style="font-size:12px;color:#333;"><?=$companys["Companyname"]?></a><br>
			
					</div>
					<!--<div class="col-xs-4">
						<a href="#" style="font-size:12px;color:#333;">Career incall 2phone Pvt.Ldt</a><br>
						<a href="#" style="font-size:12px;color:#333;">Career Monaco Telematics</a><br>
						<a href="#" style="font-size:12px;color:#333;">Career Bright Future Communication</a><br>
					</div>
					<div class="col-xs-4">
					   <a href="#" style="font-size:12px;color:#333;">Career incall 2phone Pvt.Ldt</a><br>
						<a href="#" style="font-size:12px;color:#333;">Career Monaco Telematics</a><br>
						<a href="#" style="font-size:12px;color:#333;">Career Bright Future Communication</a><br>
					</div>-->
			
			 <?php
			 }
			}
			?>
			 </div>
			<?php
			}
			 ?>
                </div>
                
               
                 
                
               
                </div>
                
                
            <div style="padding-top:40px;">
            </div>
        </div>
        
    </div>
</div>
   


<!--</header>-->
<!-- jQuery Version 1.11.0 -->

<script src="<?=URL_THEMES.'js/profile.js';?>"></script>

<script type="text/javascript">

	$(document).ready(function () {
        $("ul.nav li#dasboard-test").removeClass("active");//this will remove the active class from  
                                          
    });
 
</script>
