<style>
body {
    background: none repeat scroll 0 0 #ededed;
}
.has-error .form-control {
    border-color: #a94442;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
}

#profile .message{padding-top: 3px; font-style: italic;color: #b81900;font-size:12px;}

 .redborder{
        border:#F00 solid 1px;
        background-color:yellow;
      }
      .greenborder  {
        border:#0F3 solid 1px;
        background-color:#6F6;
      }
</style>

<!--<script src="<?=URL_THEMES.'js/companyprofile.js';?>"></script>   -->

  
  <script type="text/javascript">
    $(document).ready(function()
    {
         $("#Company_Logo_Rm").click(function() {
        if ($("#Company_Logo_Rm").is(":checked"))
                {
                     $("#Company_Logo_file").css("display","");
                    // $('#hidSaveOrUpload').val(1);
                }else
                    {
                       $("#Company_Logo_file").css("display","none");  
                       //('#hidSaveOrUpload').val(0);
                    }
        });
        
      // $('#file1').val($('#file').val());
    });
  </script>

<?php
$company=$this->company;
$countrylist=$this->countrylist;
$stateUnitedState = $this->stateUSList;
?>
<script>
    var compState = "<?=$company["state"]?>";
    var compZipcode = "<?=$company["Zipcode"]?>";
</script>
<!--<header class="subhead" id="overview">-->
 


<div class="container" >       
            
<div class="page-header" style="margin:0;">
    <h1>
        <span class="text-left" style="font-size: 25px;color: #2a6496"><?= $company["Companyname"]?> Profile</span>
        

    </h1>
</div>
    <div class="col-md-8"  style="background:#ffffff;margin-top:15px;margin-botton:50px;border-radius: 10px;">
          
      <div class="col-md-6"  style="padding:0">     

      <form enctype="multipart/form-data"   method="POST" name="profile" id="profile"  action="<?= URL_BASE . 'companyprofile/do-edit-profile'?>" role="form">
      
     <!-- <input type="hidden" id="hidSaveOrUpload" name="hidSaveOrUpload" value="0" />-->
             <div class="form-group">
                <label for="credential">Company Name</label>
              <div class="form-group">
              <input type="hidden" class="form-control" id="CompanyID" name="CompanyID" value="<?=$company["CompanyID"]?>">
                <input type="text" class="form-control" id="Companyname" name="Companyname" value="<?=$company["Companyname"]?>" >
                <span class="message" id=""></span>
              </div>
            </div>
            <div class="form-group">
                <label for="email">Industry</label>
              <div class="form-group">
                <input type="text" class="form-control" id="Industry" name="Industry" value="<?=$company["Industry"]?>" >
                 <span class="message" id=""></span>
              </div>
            </div>
			<div class="form-group">
                <label for="email">Country</label>
              <div class="form-group">
                <!--<input type="text" class="form-control" id="country" name="country" value="<?=$company["country"]?>" >-->
				<select class="form-control" id="country" name="country">
					<?php
						if(!empty($countrylist)){
							foreach($countrylist as $countrys){
					?>
						<option value="<?=$countrys["code"]?>" <?php if($company["country"]==$countrys["name"]) echo "selected"?>><?=$countrys["name"]?></option>
					<?php
							}
						}
					?>
				</select>
                 <span class="message" id=""></span>
              </div>
            </div>
            <div class="form-group ">
                <label >Address</label>
              <div class="form-group">
              
                <input name="Address"  class="form-control" id="Address" value="<?=$company["Address"]?>">
               
              </div>
            </div>
           
            
			<div class="form-group">
                <label for="email">City</label>
              <div class="form-group">
                <input type="text" class="form-control" id="city" name="city" value="<?=$company["city"]?>" >
                 <span class="message" id=""></span>
              </div>
            </div>
			<div class="col-md-6" style="padding:0;padding-right:5px">
			<div class="form-group">
                <label>State</label>
              <div class="form-group state-united-states">
                  <?php
                  if($company["country"]!='United States'){?>
                <input type="text" class="form-control" id="state" name="state" value="<?=$company["state"]?>" >
                  <?php } else{ ?>
                      <select class="form-control" id="state" name="state">
                          <option value="">Select State</option>
                          <?php
                          foreach($stateUnitedState as $kk=>$stateInfo){ ?>
                              <option value="<?=$stateInfo['state_code']?>" <?= ($stateInfo['state_name'] == $company['state']) ? 'selected="selected"' : '' ?> ><?=$stateInfo['state_name']?></option> ;
                          <?php  }
                          ?>
                      </select>
                 <?php }?>
                 <span class="message" id=""></span>
              </div>
            </div>
			
            </div>
			<div class="col-md-6 form-group" style="padding:0;padding-left:5px">
                <label for="email">Zip code</label>
              <div class="form-group">
                <input type="text" class="form-control" id="Zipcode" name="Zipcode" value="<?=$company["Zipcode"]?>" >
                 <span class="message" id=""></span>
              </div>
            </div>
            <div class="form-group">
                <label for="credential">Phone</label>
              <div class="form-group">
                <input type="text" class="form-control" id="PhoneNumber" name="PhoneNumber" value="<?=$company["PhoneNumber"]?>"  >
                 <span class="message" id="PhoneNumber_message"></span>
              </div>
                
            </div>
             <div class="form-group">
                <label for="credential">Email Info</label>
                <div class="form-group">
                <input type="text" class="form-control" id="emailinfo" name="emailinfo" value="<?=$company["emailinfo"]?>">
                 <span class="message" id="Email1_message"></span>
              </div>
                
            </div>
            <div class="form-group">
                <label for="credential">Logo</label>
                
                <div class="form-group">
                <?php
                    if($company["images"]=="")
                    {
                        
                    
                ?>
                <img width="150px" class="" src="<?=URL_MEDIA_COMPANY_PROFILE?>none.png" id="Image1" /><br/>
                <input type="hidden" id="hidFileName" name="photo" value="none.png" />
                
               
            <?php
                    }else{
           
            ?>
            <img width="110px" height="144px" class="user_photo" src="<?=URL_MEDIA_COMPANY_PROFILE.$company["images"]?>" id="Image1" /><br/>
            <input type="hidden" id="hidFileName" name="photo" value="<?= $company["images"] ?>" />
            
           
           <?php
                    }
           ?>
             <!-- <input type="checkbox" value="1" id="Company_Logo_Rm" name="Company_Logo_Rm"/> Remove &nbsp;
              <div id="Company_Logo_file" style="display:<?=empty($company["images"])?'':'none'?>; ">
                                    <!--<input type="file" name="images" id="images" > -->
              
             <!-- <input type="file" size="30"   name="file" id="file">-->
             <input type="file" size="30"   name="images" id="images">  
                                    
              <!--</div> -->
                               
                
                 <span class="message" id=""></span>
              </div>
                
            </div>
            <!--<input type="file" size="30"   name="images" id="images">  -->
            <div class="form-group">
                <label for="credential">Decription</label>
                <div class="form-group">
                
                <textarea class="form-control" rows="3" name="Description" id="Description">
                    <?=$company["Description"]?>
                </textarea>
                 <span class="message" id=""></span>
              </div>
                
            </div>
             
           <div >
           
		
			<span><button class="btn btn-success" type="submit" id="submit" name="submit"><strong>Update</strong></button></span>
			<span style="padding-left:10px"><button class="btn btn-success" id="Cancle" style="cursor:pointer;" onclick="document.location='profile'"><strong>Cancel</strong></button></span>

		
           </div>
                        
        </form>
            <div style="padding-top:20px;">
            </div>
       
        
        </div>
    </div>
</div>
<div style="padding-top:40px;">
      </div>

<!--</header>-->
<!-- jQuery Version 1.11.0 -->
<script type="text/javascript">
 $(document).ready(function () {
     var error = false; 
         $('#emailinfo').blur(function () {

         if($('#emailinfo').val()!=='')
         {
            
            var x = $('#emailinfo').val();
            var atpos = x.indexOf("@");
            var dotpos = x.lastIndexOf(".");
            
            if(atpos<1 || dotpos<atpos+2 || dotpos+2>=x.length){
                error = true;
                $("#Email1_message").addClass('has-error');
                $("#Email1_message").html("Email info is not a valid email address");
                }else{
                $("#Email1_message").removeClass('has-error').addClass('has-success');
                $("#Email1_message").html('');
            }  
         }
             
             
        });
        //
       $('#PhoneNumber').blur(function () {
            //var error = false; 
            var phone=$('#PhoneNumber').val();
            var phoneno = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/; 
            if (!phone.match(phoneno) && phone.length >1) {
                error = true;
                $('#PhoneNumber_message').addClass('has-error');
                $("#PhoneNumber_message").html("Phone Number must be a valid 10 digit number with optional extension similar to XXX XXX XXXX ");
                
            }else{
                            
               $("#PhoneNumber_message").removeClass('has-error').addClass('has-success');
                $("#PhoneNumber_message").html('');
            }
        });
        $( "#profile" ).submit(function( event ) {
                //alert( "Handler for .submit() called." );
                //event.preventDefault();
                if($('#emailinfo').val()!=='')
                 {
                    var x = $('#emailinfo').val();
                    var atpos = x.indexOf("@");
                    var dotpos = x.lastIndexOf(".");
                    
                    if(atpos<1 || dotpos<atpos+2 || dotpos+2>=x.length){
                        error = true;
                        $("#Email1_message").addClass('has-error');
                        $("#Email1_message").html("Email info is not a valid email address");
                        event.preventDefault();
                        }else{
                        $("#Email1_message").removeClass('has-error').addClass('has-success');
                        $("#Email1_message").html('');
                    }  
                 }
                 var phone=$('#PhoneNumber').val();
            var phoneno = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/; 
            if (!phone.match(phoneno) && phone.length >1) {
                error = true;
                $('#PhoneNumber_message').addClass('has-error');
                $("#PhoneNumber_message").html("Phone Number must be a valid 10 digit number with optional extension similar                  to XXX XXX XXXX ");
                event.preventDefault();
                
            }else{
                            
               $("#PhoneNumber_message").removeClass('has-error').addClass('has-success');
                $("#PhoneNumber_message").html('');
            }
               
});

     $("#country").unbind('change').bind('change',function(){
      var countryCode = $(this).val();
      if(countryCode !='US'){
          var html ="";
          html +='<input type="text" class="form-control" id="state" name="state" value="'+compState+'" >' +
              '<span class="message" id=""></span>';

          $('.state-united-states').html(html);
          $('#Zipcode').val(compZipcode);

      } else{
          $.ajax({
              url: 'get-state-united-list',
              dataType    : 'json',
              data: {countryCode: 'US'},
              type: 'POST',
              error : function (data,xhr,error) {
                   var html ="";
                   html +='<input type="text" class="form-control" id="state" name="state" value="" >' +
                   '<span class="message" id=""></span>';

                  $('.state-united-states').html(html);
                  $('#Zipcode').val("");
              },
              success: function(data, status, xhr){
                  if(data){
                      var html = '<select class="form-control" id="state" name="state"><option value="">Select State</option>';

                      $.each(data,function(k,stateInfo){
                         html +='<option value="'+stateInfo.state_code+'">'+stateInfo.state_name+'</option>';
                      });

                        html +='</select><span class="message" id=""></span>';
                      $('.state-united-states').html(html);
                      $('#Zipcode').val("");
                  }
              }
          });

      }


     });

 });

</script>




