<style>

.has-error .form-control1 {
    border-color: #a94442;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
}

#profile .message{padding-top: 3px; font-style: italic;color: #b81900;font-size:12px;}

 .redborder{
        border:#F00 solid 1px;
        background-color:yellow;
      }
      .greenborder  {
        border:#0F3 solid 1px;
        background-color:#6F6;
      }
</style>

<!--<script src="<?=URL_THEMES.'js/companyprofile.js';?>"></script>   -->

  
  <script type="text/javascript">
    $(document).ready(function()
    {
         $("#Company_Logo_Rm").click(function() {
        if ($("#Company_Logo_Rm").is(":checked"))
                {
                     $("#Company_Logo_file").css("display","");
                    // $('#hidSaveOrUpload').val(1);
                }else
                    {
                       $("#Company_Logo_file").css("display","none");  
                       //('#hidSaveOrUpload').val(0);
                    }
        });
        
      // $('#file1').val($('#file').val());
    });
  </script>

<?php
$company=$this->company;

?>
<!--<header class="subhead" id="overview">-->
 


<div class="container" >       
            
<div class="page-header" style="margin:0;">
    <h1>
        <span class="text-left" style="font-size: 25px;color: #2a6496"><?= $company["Companyname"]?> Profile</span>
        

    </h1>
</div>
    <div class="col-md-8"  style="background:#ffffff;margin-top:15px;margin-botton:50px;">
          
      <div class="col-md-6"  style="padding:0">     

      <form enctype="multipart/form-data"   method="POST" name="profile" id="profile"  action="<?= URL_BASE . 'companyprofile/do-edit-profile'?>" role="form">
      
     <!-- <input type="hidden" id="hidSaveOrUpload" name="hidSaveOrUpload" value="0" />-->
             <div class="form-group">
                <label for="credential">Company Name</label>
              <div class="form-group">
              <input type="hidden" class="form-control" id="CompanyID" name="CompanyID" value="<?=$company["CompanyID"]?>">
                <input type="text" class="form-control" id="Companyname" name="Companyname" value="<?=$company["Companyname"]?>" >
                <span class="message" id=""></span>
              </div>
            </div>
            <div class="form-group">
                <label for="email">Industry</label>
              <div class="form-group">
                <input type="text" class="form-control" id="Industry" name="Industry" value="<?=$company["Industry"]?>" >
                 <span class="message" id=""></span>
              </div>
            </div>
            <div class="form-group ">
                <label >Address</label>
              <div class="form-group">
              
                <input name="Address"  class="form-control" id="Address" value="<?=$company["Address"]?>">
               
              </div>
              <div class="form-group ">
                <label >Zipcode</label>
              <div class="form-group">
              
                <input name="Zipcode"  class="form-control" id="Zipcode" value="<?=$company["Zipcode"]?>">
               
              </div>
            </div>
           
            <div class="form-group">
                <label for="email">Country</label>
              <div class="form-group">
                <input type="text" class="form-control" id="country" name="country" value="<?=$company["country"]?>" >
                 <span class="message" id=""></span>
              </div>
            </div>
            
            <div class="form-group">
                <label for="credential">Phone</label>
              <div class="form-group">
                <input type="text" class="form-control" id="PhoneNumber" name="PhoneNumber" value="<?=$company["PhoneNumber"]?>"  >
                 <span class="message" id=""></span>
              </div>
                
            </div>
             <div class="form-group">
                <label for="credential">Email Info</label>
                <div class="form-group">
                <input type="text" class="form-control" id="emailinfo" name="emailinfo" value="<?=$company["emailinfo"]?>">
                 <span class="message" id=""></span>
              </div>
                
            </div>
            <div class="form-group">
                <label for="credential">Logo</label>
                
                <div class="form-group">
                <?php
                    if($company["images"]=="")
                    {
                        
                    
                ?>
                <img width="150px" class="" src="<?=URL_MEDIA_COMPANY_PROFILE?>none.png" id="Image1" /><br/>
                <input type="hidden" id="hidFileName" name="photo" value="none.png" />
                
               
            <?php
                    }else{
           
            ?>
            <img width="110px" height="144px" class="user_photo" src="<?=URL_MEDIA_COMPANY_PROFILE.$company["images"]?>" id="Image1" /><br/>
            <input type="hidden" id="hidFileName" name="photo" value="<?= $company["images"] ?>" />
            
           
           <?php
                    }
           ?>
              <input type="checkbox" value="1" id="Company_Logo_Rm" name="Company_Logo_Rm"/> Remove &nbsp;
              <div id="Company_Logo_file" style="display:<?=empty($company["images"])?'':'none'?>; ">
                                    <!--<input type="file" name="images" id="images" > -->
              
             <!-- <input type="file" size="30"   name="file" id="file">-->
             <input type="file" size="30"   name="images" id="images">  
                                    
              </div> 
                               
                
                 <span class="message" id=""></span>
              </div>
                
            </div>
            <!--<input type="file" size="30"   name="images" id="images">  -->
            <div class="form-group">
                <label for="credential">Decription</label>
                <div class="form-group">
                
                <textarea class="form-control" rows="3" name="Description" id="Description">
                    <?=$company["Description"]?>
                </textarea>
                 <span class="message" id=""></span>
              </div>
                
            </div>
             
           <div class="">
           
                    
                        <button class="btn btn-success" type="submit" id="submit" name="submit">Update</button>

                    
           </div>
                        
        </form>
       
        
        </div>
    </div>
      </div>

<!--</header>-->
<!-- jQuery Version 1.11.0 -->




