<script src="<?=URL_THEMES.'js/mobile.notifications.js';?>"></script>
<?php
//$result = $this->result;
///$clientIDLogin = $this->clientIDLogin;
//$userName = $this->userName;
$companylists = $this->companylists;
?>
<style>
    .panel {
        background-color: #fff;
        border: 1px solid transparent;
        border-radius: 4px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
        margin-bottom: 20px;
    }
.clWidth200{width: 200px;}
.clWidth300{width: 300px;}
 .clWidth600{width: 400px;}
    .rowHeight { margin-bottom: 3px!important; margin-top: 3px!important}
</style>
<!-- Modal Add -->
<div class="container">

<div style="height:80px; color: #2a6496">
    <div class="panel-body">
        <div><h3 style="margin-top: 10px; margin-left: -16px"><label>List Company</label> </h3></div>
        <div style="float: right; margin-top: -37px; margin-right:-10px">
            <a href="<?= URL_BASE ?>companyprofile/addcompany"><button class="btn btn-success" type="button">Add Company</button></a>

        </div>
    </div>
</div>
<header class="subhead" id="overview">
    <div class="panel panel-primary" style="border:0;margin-bottom: 0px">
            <div class="panel-heading" style="background-color: #2a6496">
                <h3 class="panel-title">
                    <strong>Company Box</strong>
                </h3>
            </div>

        </div>
    </header>

        <table id="notificationCk"  style="background-color: #fff" class="table  table-bordered" cellspacing="0" width="100%" style="border-top-color: #eeeeee">
            <thead>
            <tr role="row" >
                <th class="clWidth300 ">
                    <label>
                        <strong>Company Name</strong>
                    </label>
                </th>
                <th class="clWidth600 ">
                    <label>
                        <strong>Address</strong>
                    </label>
                </th>
                <th class="clWidth600 ">
                    <label>
                        <strong>Industry</strong>
                    </label>
                </th>
                <th  class="clWidth200 text-center">
                    <label>
                        <strong>Action</strong>
                    </label>
                   <!-- <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="border-color: #fff; ">
                            <strong>Action </strong><span class="caret"></span>
                        </button>
                        
                    </div>    -->
                </th>
            </tr>
            </thead>
            <tbody>
            <?php
            if(!empty($companylists)){
                foreach($companylists as $key=>$companys){
            
            ?>
                <tr role="row" class="odd ischecktr">
                    <td class="clWidth300 ">
                        <input type="hidden" name="CompanyID" value="<?= $companys["CompanyID"]?>">
                        <span style="padding-left:10px"><strong><a href="<?= URL_BASE ?>companyprofile/profile?companyid=<?= $companys["CompanyID"] ?>&pageajax=profile"><?= $companys["Companyname"]?></a></strong></span> 
                    </td>
                    <td class="clWidth600 "><span class="notiText"><?=$companys["Address"]?></span></td>
                    <td class="clWidth200 "><?=$companys["Industry"]?></td>
                    <td class="clWidth200"  align="center"><span><a href="<?= URL_BASE ?>companyprofile/editprofile?companyid=<?= $companys["CompanyID"] ?>&pageajax=editprofile"><img src="<?=URL_THEMES?>images/update.PNG"></a></span><a href="<?= URL_BASE ?>companyprofile/deletecompany?companyid=<?= $companys["CompanyID"] ?>" style=" color:#ccc; padding-left:8px" class="glyphicon glyphicon-remove glyphiconDelete deleteYes" onclick="return confirm('Are you sure delete?')"></a></td>
                </tr>
            <?php
            
            
            }
            }
            
            ?>
            </tbody>
        </table>
       <!-- <div class="" style="height: 40px;background-color: #333">

        </div>  -->
</div>

