<style>



    .label-tag{
        border: 1px solid #ddd; padding: 3px;
        background-color: #eee;
        color: #000;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        margin-right: 10px;margin-bottom: 5px;text-decoration: underline;
    }
    .tag-remove{cursor: pointer; }
    .tag-remove:hover{color: #777}
    .btn-matches{ margin-top: 20px;background-color: #20B2AA;padding: 7px 50px; color: #fff; border: 1px solid #eee}
    .btn-matches:hover{}
</style>
<div class="container" >

<!--
    <div  style="height:80px; color: #428bca">
        <div class="panel-body">
            <div><h3 style="margin-top: 10px"><strong></strong> <span class="name-edit" > <i class="glyphicon glyphicon-pencil"></i></span></h3></div>
            <div style="float: right; margin-top: -35px; margin-right:-10px">
            <button class="btn btn-sm btn-success" type="button"><strong>Create New Test</strong></button>

            </div>
        </div>
    </div> -->
<!--
    <div style="height:80px; color: #2a6496">
        <div class="panel-body">
            <div><h3 style="margin-top: 10px; margin-left: -16px"><label></label> </h3></div>
            <div style="float: right; margin-top: -30px; margin-right:-10px">
                <button class="btn btn-success" type="button">Create New Test</button>

            </div>
        </div>
    </div> -->
    <div class="row" style="padding-top: 40px">
        <div class="col-md-12"><h2><a><strong>Dashboard</strong></a></h2></div>

    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body">
                    <div class="col-md-8">
                        <h2><strong>Welcome! to Pocket Cruiter</strong></h2>
                        <small>Donec puere sapien nibh donec puere sapien nibh, nec imperdieDonec puere <br/>sapien nibh donec puere sapien nibh, nec imperdiDonec puere sapien <br/>nibh donec puere sapien nibh, nec imperdi</small>
                        <p><button type="button" class="btn  btn-matches"><strong>Show Matches Now</strong></button></p>
                    </div>
                    <div class="col-md-4">
                        <div class="alert alert-warning fade in" role="alert">
                            <h4><strong>Need Help!</strong></h4>
                            <span style="color: #333"><strong>Published Recruiter Post Here</strong></span>
                            <a style="text-decoration: underline; color: #333;font-size: 12px;padding-left: 20px">Donec puere sapien nibh donec puer</a>
                            <span style="color: #333"><strong>Published Recruiter Post Here</strong></span>
                            <a style="text-decoration: underline; color: #333;font-size: 12px;padding-left: 20px">Donec puere sapien nibh donec puer</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">

       <div class="col-md-4">
           <div class="panel  panel-default">
            <div class="panel-heading" style="background-color: #2a6496;color: #fff ">Pocket Recruiter Introduction</div>
            <div class="panel-body" style="height: 300px;">
               <h1><span style="color: #357ebd">Start Profile...</span></h1>
               <h4>Donec puere sapien nibh donec puere sapien nibh, nec imperdie</h4>
               <br>
               <div style="color: #777">
                  puere sapien nibh donec puere sapien nibh, nec imperdie
                   puere sapien nibh donec puere sapien nibh, nec imperdie
                   puere sapien nibh donec puere sapien nibh, nec imperdie

               </div>
                <p >
                <button class="btn btn-success"><strong>Start Here</strong></button></p>
           </div>
           </div>
       </div>
        <div class="col-md-4">
            <div class="panel  panel-default">
                <div class="panel-heading" style="background-color: #2a6496;color: #fff ">Pocket Recruiter Introduction</div>
                <div class="panel-body" style="height: 300px;">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>
                                    <span class="pull-left">
                                        <label><input type="checkbox" name="" value=""/> Check All</label>
                                    </span>
                                    <span class="pull-right"><span class="dropdown">
                                       Action<span style="cursor:pointer" data-toggle="dropdown" class="caret"></span>
                                        <ul  class="dropdown-menu" role="menu">
                                            <li><a id="test-act-remove" href="javascript: void(0)">Delete</a></li>
                                            <li><a id="test-act-assign" href="javascript: void(0)">Assign</a></li>
                                        </ul>
                                    </span></span>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><label><input type="checkbox" name="" value=""/> Adrey Abbot </label> Test 12121</td>
                            </tr>
                            <tr>
                                <td><label><input type="checkbox" name="" value=""/> Adrey Abbot </label> Test 12121</td>
                            </tr>
                            <tr>
                                <td><label><input type="checkbox" name="" value=""/> Adrey Abbot </label> Test 12121</td>
                            </tr>
                            <tr>
                                <td><label><input type="checkbox" name="" value=""/> Adrey Abbot </label> Test 12121</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel  panel-default">
                <div class="panel-heading" style="background-color: #2a6496;color: #fff ">Technical Tests</div>
                <div class="panel-body" style="height: 300px;">
                    <span class="label-tag pull-left">Testing <i class="glyphicon glyphicon-remove text-right tag-remove"></i></span>
                    <span class="label-tag pull-left">Abbot <i class="glyphicon glyphicon-remove text-right tag-remove"></i></span>
                    <span class="label-tag pull-left">Mongo <i class="glyphicon glyphicon-remove text-right tag-remove"></i></span>
                    <span class="label-tag pull-left">Tiddy <i class="glyphicon glyphicon-remove text-right tag-remove"></i></span>
                    <p class="pull-left" style="width: 100%;position: absolute;bottom: 20px;">
                        <button class="btn btn-primary">Create New Test</button>
                    </p>
                </div>

            </div>
        </div>
    </div>

    <div class="panel-group" id="accordion">

        <div class="panel panel-default">
            <div class="panel-heading" style="background-color: #2a6496;color: #fff">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                        <strong>Save Test</strong>
                    </a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse  collapse in">
                <div>
                    <div class="table-responsive">

                        <table id="test-list" style="margin-bottom:0;"  class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th class="clWidth200"><span><input type="checkbox" id="all-check" name=""/>Select All</span></th>
                                <th class="clWidth200"><strong>Test Name</strong></th>
                                <th></th>
                                <th>Question</th>
                                <th>
                                    <span class="dropdown">
                                       Action<span class="caret" data-toggle="dropdown" class="link" style="cursor:pointer"></span>
                                        <ul role="menu" class="dropdown-menu" style="left:-68px;">
                                            <li><a href="javascript: void(0)" id="test-act-remove">Delete</a></li>
                                            <li><a href="javascript: void(0)" id="test-act-assign">Assign</a></li>
                                        </ul>
                                    </span>

                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if(!empty($this->list)){ foreach($this->list as $key=>$item){ ?>
                                <tr>
                                    <td class="clWidth200">
                                        <span><input type="checkbox" data-text="<?=$item['TestName'];?>" data-id="<?=$item['TestID'];?>"/>
                                            <strong>
                                                <?php
                                                    $time = strtotime($item['posteddate']);
                                                    echo date("m/d/y", $time);
                                                ?>
                                            </strong>
                                        </span>
                                        <span class="pull-right"><i class="glyphicon glyphicon-eye-open" style="color: #bbb"></i></span>
                                    </td>
                                    <td class="clWidth200"><a href="#" style="text-decoration: underline; color: #777">
                                            <?=$item['TestName'];?>
                                    </a></td>
                                    <td style="color: #777"></td>
                                    <td class="clWidth100"><strong>Q. &nbsp<?=$item['NumQuestions'];?></strong></td>
                                    <td class="clWidth100">
                                        <span class="btn-edit" data-id="<?=$item['TestID'];?>" style="color: #4cae4c"><strong>Edit</strong></span> &nbsp;&nbsp;
                                        <span><i data-text="<?=$item['TestName'];?>" data-id="<?=$item['TestID'];?>" class="glyphicon glyphicon-remove qst-remove"></i></span>
                                    </td>
                                </tr>
                            <?php } } ?>
                            </tbody>
                        </table>
                        <!--<div class="" style="height: 40px;background-color: #333">-->
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

</div>
<script src="<?=URL_THEMES.'js/pocket.dashboard.js';?>"></script>
<script>

</script>
