<script src="<?=URL_THEMES.'js/mobile.career.js';?>"></script>


<style>
    a {
        color: #fff;
        text-decoration: none;
    }
    .nav-tabs {
        border-bottom: 1px solid #ddd;
    }

    .nav-tabs>li.active>a, .nav-tabs>li.active>a:hover, .nav-tabs>li.active>a:focus {
        color: #428bca;
        background-color: #fff;
       /*  border: 1px solid #ddd;*/
        border-bottom-color: transparent;
    }
    .nav-tabs>li>a {
        margin-right: 2px;
        line-height: 1.428571429;
        border: 1px solid transparent;
        border-radius: 4px 4px 0 0;
    }
    .table-striped > tbody > tr:nth-child(2n+1) > td, .table-striped > tbody > tr:nth-child(2n+1) > th {
        background-color:#f7ecb5;
    }
    .table-stripedgray > tbody > tr:nth-child(2n) > td, .table-striped > tbody > tr:nth-child(2n) > th {
        background-color:#eeeeee;
    }
    #requiredSkillClass {
        min-height: 80px!important; height:auto;
        border: 1px solid #cccccc;
    }
    #requiredTest {
        min-height: 80px!important; height:auto;
        border: 1px solid #cccccc;
    }

    .menuBar {  background-image:url("<?=URL_THEMES?>images/img4.png"); background-repeat:repeat-x  ;border-radius: 4px; margin-bottom: 20px;
         box-shadow: 0 10px 8px -8px #bbb;
    }
    .menuBar ul{list-style:none}
    .menuBar ul li {float: left; width:217px; line-height:32px; margin-left:-20px;}
    .menuBar li a {color: #777; float: left; text-indent:15px; margin-left: -34px; width:200px; text-decoration: none; background-image:url("<?=URL_THEMES?>images/tab2.png")}

    .menuBar li a:active { background-color:#003399 ;color:#fff; text-decoration:none}
    .menuBar ul li .active { color:#fff!important; text-decoration:none; width:200px; background-image:url("<?=URL_THEMES?>images/createCareer_b.png") }
    .tabendBetween {background-image:url("<?=URL_THEMES?>images/tab4.png")!important; z-index: 10000}
    .tabend {background-image:url("<?=URL_THEMES?>images/tabend.png")!important; z-index: 10000}

    .label-tag{
        border: 1px solid #ddd; padding: 3px;
        background-color: #eee;
        color: #000;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        margin-right: 10px;margin-bottom: 5px;
    }
    .colorBlue {color: #2a6496;}
</style>

<div class="container">
    <div style="height:80px; color: #2a6496">
        <div class="panel-body" style="padding-left: 0px">
            <div style="padding-left: 0px"><h3 style="margin-top: 22px;"><label>Post Opportunity</label> </h3></div>
        </div>
    </div>

    <div style="background-color: #2a6496">
        <ul class="nav nav-tabs"  style="padding-top:10px" valign="bottom">
            <li class="active" ><a class="calcareercr" href="javascript: void(0);"><strong>New Opportunity</strong></a></li>
            <li ><a id="careerlist" href="javascript: void(0);"><strong>Opportunity List</strong></a></li>
        </ul>
    </div>

        <!--create career-->
    <div class="panel panel-default">
          <div class="panel-body">
                <div class="col-md-12">
                    <div class="menuBar col-md-12">
                    <ul  id="careerTab">
                        <li class="active"><a class="active" href="#calcareercr" id="calcareercrtab"><strong>1. Create Opportunity &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></a></li>
                        <li><a href="#" id="createPrivate"><strong>&nbsp;2. Create Private &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></a></li>
                        <li><a  href="#previewpost" id="previewposttab"><strong>&nbsp;3. Preview &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></a></li>
                    </ul>
                    </div>
                </div>

                <div class="tab-content">
                     <!--Career Create new  -->
                      <div id="calcareercr" class="tab-pane active">
                            <!--LEFT-->

                            <div class="col-md-8">
                                <form id="form-careerCr" name="form-careerCr">
                                    <div class="col-md-12">
                                        <label >Opportunity Name* </label> <span id="careernameLable" style="color: red"> </span>
                                        <input type="text"  id="careername" name="careername" class="form-control">
                                    </div>
                                    <div class="col-md-12" style="margin-top: 5px; margin-bottom: 5px">
                                        <div class="col-md-7" style="padding-left: 0px; padding-top: 10px">
                                            <label >Company Name* </label><span id="companynameLable" style="color: red"></span>
                                        </div>

                                    </div>
                                    <div class="col-md-12">

                                        <input type="text"  readonly="true" id="companyname" name="companyname" value="<?=$this->companyInfo['Companyname']?>" class="form-control">
                                        <input type="hidden" name="CompanyID" value="<?=$this->companyInfo['CompanyID']?>">
                                    </div>
                                    <div class="col-md-12">
                                        <label >Opportunity Description*</label><span id="careerdescriptionLable" style="color: red"></span>
                                        <textarea style=" height: 80px" id="careerdescription" name="careerdescription" class="form-control"></textarea>
                                    </div>
                                   <!-- <div class="col-md-12" style="margin-top: 5px; margin-bottom: 5px">
                                        <span style=" float:right"><input type="file" title="Add Attachment"  class="colorBlue" ></span>
                                    </div> -->
                                    <div class="col-md-12">
                                        <label>Opportunity Industry*</label> <span id="industryLable" style="color: red"></span>
                                        <input type="text" id="industry" name="industry" class="form-control">
                                    </div>
                                    <div class="col-md-12" style="margin:0;padding:0">
                                        <div class="col-md-6" >
                                            <label>Opportunity Type </label>
                                            <select id="careerType" name="jobtype" class="form-control">
                                                <?php
                                                $careerType =  $this->resultCareerList;
                                                foreach ($careerType as $k =>$careerInfo){
                                                    ?>
                                                    <option value="<?=$careerInfo['CareertypeID']?>"><?=$careerInfo['CareertypeName']?></option>
                                                <?php
                                                }
                                                ?>
                                            </select>
                                        </div>
                                        <div class="col-md-6">
                                            <label>Duration</label>
                                            <select name="duration" id="durationTime" class="form-control">
                                                <option value ="1ngay" >1 Day </option>
                                                <option value ="2ngay" >2 Days </option>
                                                <option value ="3ngay" >3 Days </option>
                                                <option value ="1year" >1 Year </option>
                                                <option value ="5year" >5 Year </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-12" style="margin:0;padding:0">
                                        <div class="col-md-6">
                                            <label>Opportunity Location </label>
                                            <input id="loacation" name="location" type="text"  class="form-control">
                                        </div>
                                        <div class="col-md-6">
                                            <label>Opportunity Zip Code</label>
                                            <input id="zipcode" name="zipcode" type="text" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-12" style="margin:0;padding:0">
                                        <div class="col-md-6">
                                            <label>Country </label>
                                            <select name="country" id="country" class="form-control">
                                                <?php
                                                if($this->listCountry !=""){
                                                    foreach($this->listCountry as $CK=>$countryInfo){
                                                        ?>
                                                        <option value ="<?=$countryInfo['code']?>" ><?=$countryInfo['name']?> </option>
                                                <?php
                                                    }
                                                }
                                                ?>


                                            </select>
                                        </div>
                                        <div class="col-md-6">
                                            <label>City</label>
                                            <input id="city" name="city" type="text" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <label >Minimum Education*</label> <span id="minimuneducationLable" style="color: red"></span>
                                        <input id="minimuneducation" name="minimuneducation" type="text" class="form-control">
                                    </div>
                                    <div class="col-md-12">
                                        <label >Degree Title*</label> <span id="degreetitleLable" style="color: red"></span>
                                        <input id="degreetitle" name="degreetitle" type="text" class="form-control">
                                    </div>
                                    <div class="col-md-12" style="margin-top: 5px; margin-bottom: 5px">
                                        <div class="col-md-9" style="margin:0;padding:0;padding-top:5px"><strong >Required Skills*</strong> <span id="requiredSkillLable" style="color: red"></span>
                                        </div>
                                        <div class="col-md-3" style="padding-right:0px">
                                            <select id="selectSkill" class="form-control">
                                                <option value="">Select Skill</option>
                                                <?php
                                                $SkillList = $this->resultSkillList;
                                                foreach ($SkillList as $k=>$skillInfo) {
                                                    ?>
                                                    <option value="<?=$skillInfo['SkillID']?>" ><?=$skillInfo['SkillName']?></option>
                                                <?php
                                                }

                                                ?>
                                            </select>
                                        </div>

                                    </div>
                                    <div class="col-md-12" >
                                        <div id="requiredSkillClass" class="form-control">



                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <label >Required Experience*</label><span id="requiredExperienceLable" style="color: red"></span>
                                        <select  id="requiredExperience" name="requiredExperience" class="form-control">
                                            <?php
                                            $listExperienced = $this->listExperienced;
                                            if($listExperienced !=""){
                                                foreach ($listExperienced as $ek=>$listExperiencedInfo) {
                                                    ?>
                                                    <option value="<?=$listExperiencedInfo['experience_id']?>"> <?=$listExperiencedInfo['experience_descrip']?></option>
                                                <?php
                                                }
                                            }

                                            ?>

                                        </select>
                                    </div>
                                    <div class="col-md-12" style="margin:0;padding:0">
                                        <div class="col-md-6">
                                            <label >Salary Range*</label> <span id="salaryRangeLable" style="color: red"></span>
                                            <select  id="salaryRangeF" name="salaryRangeF" class="form-control">
                                                <option value="10"> 10 K</option>
                                                <option value="20"> 20 K</option>
                                                <option value="30"> 30 K</option>
                                                <option value="40"> 40 K</option>
                                                <option value="50"> 50 K</option>
                                                <option value="60"> 60 K</option>
                                                <option value="70"> 70 K</option>
                                                <option value="80"> 80 K</option>
                                                <option value="90"> 90 K</option>
                                                <option value="100"> 100 K</option>
                                            </select>
                                        </div>
                                        <div class="col-md-6">
                                            <label>&nbsp;</label>
                                            <select id="salaryRangeT" name="salaryRangeT" class="form-control">
                                                <option value="10"> 10 K</option>
                                                <option value="20"> 20 K</option>
                                                <option value="30"> 30 K</option>
                                                <option value="40"> 40 K</option>
                                                <option value="50"> 50 K</option>
                                                <option value="60"> 60 K</option>
                                                <option value="70"> 70 K</option>
                                                <option value="80"> 80 K</option>
                                                <option value="90"> 90 K</option>
                                                <option value="100"> 100 K</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-md-12" style="margin-top: 5px; margin-bottom: 5px">
                                        <div class="col-md-9" style="margin:0;padding:0; padding-top:5px"><label>Required Test</label></div>
                                        <div class="col-md-3" style="padding-right: 0px">
                                            <select id="selectRequiredTest" class="form-control">
                                                <option value="">Select Test</option>
                                                <?php
                                                $testList = $this->resultTestList;
                                                foreach ($testList as $k=>$testListInfo) {
                                                    ?>
                                                    <option value="<?=$testListInfo['TestID']?>" ><?=$testListInfo['TestName']?></option>
                                                <?php
                                                }

                                                ?>
                                            </select>
                                        </div>

                                    </div>
                                    <div class="col-md-12" >
                                        <div id="requiredTest" class="form-control">



                                        </div>
                                    </div>
                                    <input type="hidden" id="career_status" name="status" value="">
                                </form>
                            </div>

                        <!-- END LEFT-->
                        <!--RIGHT-->
                        <div class="col-md-4">
                            <div class="col-md-12">
                                    <label>&nbsp;</label>
                            </div>
                            <div class="col-md-12">
                                <div style="min-height:100px; background-color: #fffbd5;" class="form-control text-left">
                                    <label style="color:#e1b903;">Need Help</label>
                                </div>
                            </div>
                        </div>
                        <!--END RIGHT-->
                        <div class="col-md-12" style="padding-left:30px; padding-top:10px">
                            <button id="careercontinue" style="width:90px" type="button" class="btn btn-primary" data-loading-text="Loading...">Continue</button>
                            <button id="savePostLater" style="width:140px; margin-left: 20px" type="button" class="btn btn-primary" data-loading-text="Loading...">Save & Post Later</button>
                        </div>
                    </div>
                    <!--end career create new-->


                    <!--Post preview-->
                    <div id="previewpost" class="tab-pane col-md-12">
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label >Opportunity Name*</label>
                                </div>
                                <div class="col-md-10" id="pp_career_name"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label >Company Name*</label>
                                </div>
                                <div class="col-md-10" id="pp_company_name"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Opportunity Description*</label>
                                </div>
                                <div class="col-md-10" id="pp_career_des"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Industry*</label>
                                </div>
                                <div class="col-md-10" id="pp_industry"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Opportunity Type</label>
                                </div>
                                <div class="col-md-10" id="pp_career_type"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Opportunity Location</label>
                                </div>
                                <div class="col-md-10" id="pp_career_location"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Minimum Education*</label>
                                </div>
                                <div class="col-md-10" id="pp_minimun_education"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Degree Title*</label>
                                </div>
                                <div class="col-md-10" id="pp_degree_title"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Required Skills*</label>
                                </div>
                                <div class="col-md-10" id="pp_required_skills"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Required Experience*</label>
                                </div>
                                <div class="col-md-10" id="pp_required_experience"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Salary Range*</label>
                                </div>
                                <div class="col-md-10" id="pp_salary_range"></div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-2" style="text-align:right">
                                    <label>Required Test</label>
                                </div>
                                <div class="col-md-10" id="pp_required_test"></div>
                            </div>

                                <button id="postcareernew" style="width:135px" type="button" class="btn btn-primary" data-loading-text="Loading..."><strong>Post Opportunity</strong></button>
                                <button id="" style="width:105px; margin-left: 20px; color: white;" type="button" class="btn " data-loading-text="Loading..."><strong>Edit Post</strong></button>
                                <button id="" style="width:170px;margin-left: 20px;color: white;" type="button" class="btn " data-loading-text="Loading..."><strong>Post Opportunity Later</strong></button>
                                <button id="" style="width:135px;margin-left: 20px;color: white;" type="button" class="btn " data-loading-text="Loading..."><strong>Save Opportunity</strong></button>

                        </div>
                    <!--end post preview-->
                </div>

          </div>
    </div>
            <!--end create career-->
</div>
    <script>
        var careerPrototype = new career();
        $("#careerTab a").unbind('click').bind('click',function(){
            $(this).tab('show');
            $('#careerTab').find('li.active').find('a').removeClass('tabend');
            $('#careerTab').find('li.active').find('a').addClass('active');
            $('#careerTab').find("li[class!='active']").find('a').removeClass('active');
            $('#careerTab').find("li[class!='active']").find('a').removeClass('tabendBetween');
            $('#careerTab').find("li[class!='active']").find('a').removeClass('tabend');
            if($(this).attr("id")=="previewposttab"){
                careerPrototype.previewPost();
                $('#careerTab').find('li.active').find('a').addClass('active');
                $('#careerTab').find('li.active').find('a').addClass('tabendBetween');
                $('#careerTab').find("li[class!='active']").find('a').removeClass('active');
                $(this).parent().prev('li').find('a').addClass('tabend');
            } else if($(this).attr("id")=="createPrivate"){
                $('#careerTab').find('li.active').find('a').addClass('active');
                $('#careerTab').find('li.active').find('a').addClass('tabendBetween');
                $('#careerTab').find('li.active').find('a').removeClass('tabend');
                $('#careerTab').find("li[class!='active']").find('a').removeClass('active');
                $(this).parent().prev('li').find('a').addClass('tabend');
            }
        });
        $("#careercontinue").unbind('click').bind('click',function(){
            $('#careerTab > .active').next('li').next('li').find('a[href="#previewpost"]').trigger('click');
            $('#careerTab').find('li.active').find('a').addClass('active');
            $('#careerTab').find("li[class!='active']").find('a').removeClass('active');
            ///careerPrototype.previewPost();
        })
        $('#careerTab').find('li.active').find('a').addClass('active');
        $('#careerTab').find("li[class!='active']").find('a').removeClass('active');

        //attachment file
       /* $('input[type=file]').bootstrapFileInput();
        $('.file-inputs').bootstrapFileInput(); */
        $('#savePostLater').unbind('click').bind('click',careerPrototype.postcareernew)
    </script>




