<script src="<?=URL_THEMES.'js/mobile.career.js';?>"></script>
<script>
    var objCareer = new career();
    $(".navbar-nav li").removeClass("active");//this will remove the active class from previously active menu item
</script>
<style>
    a {
        color: #fff;
        text-decoration: none;
    }
    .nav-tabs {
        border-bottom: 1px solid #ddd;
    }

    .nav-tabs>li.active>a, .nav-tabs>li.active>a:hover, .nav-tabs>li.active>a:focus {
        color: #428bca;
        background-color: #fff;
       /*  border: 1px solid #ddd;*/
        border-bottom-color: transparent;
    }
    .nav-tabs>li>a {
        margin-right: 2px;
        line-height: 1.428571429;
        border: 1px solid transparent;
        border-radius: 4px 4px 0 0;
    }
    .table-striped > tbody > tr:nth-child(2n+1) > td, .table-striped > tbody > tr:nth-child(2n+1) > th {
        background-color:#fffbd5;
    }
    .table-stripedgray > tbody > tr:nth-child(2n) > td, .table-striped > tbody > tr:nth-child(2n) > th {
        background-color:#eeeeee;
    }

    ol.breadcrumb a{color: #777;}
    ol.breadcrumb .active{color: #fff; background-color: #2a6496;}
    .needHelp {background-color:#edde34 ; min-height: 100px!important; height: auto; width:300px; border-left: 1px solid #cccccc; border-right: 1px solid #cccccc;
    border-bottom: 1px solid #cccccc; float:right; }
</style>
<?php
$oppportunityList = $this->getListOpp;
?>
<div class="container">
    <div style="height:80px; color: #2a6496">
        <div class="panel-body" style="padding-left: 0px">
            <div style="padding-left: 0px"><h3 style="margin-top: 22px; "><label>Post Career</label> </h3></div>
        </div>
    </div>
    <div style="background-color: #2a6496">
        <ul class="nav nav-tabs" id="myTab" style="padding-top:10px" valign="bottom">
            <li  ><a class="calcareercr" href="javascript: void(0);"><strong>New Opportunity</strong></a></li>
            <li class="active"><a id="careerlist" href="javascript: void(0);"><strong>Opportunity List</strong></a></li>
        </ul>
    </div>
    <div class="tab-content">
            <!-- career list-->
            <div class="tab-pane active" >
                <table class="table table-striped  table-stripedgray table-bordered" cellspacing="0" width="100%" style="border-top-color: #eeeeee">
                    <thead>
                    <tr role="row" style="background-color: #eeeeee">
                        <th style="width:135px">
                            <label>
                            <input type="checkbox"> <strong>Select All</strong>
                            </label>
                        </th>
                        <th style="width:120px">
                                <label>
                                     <strong>Career Title</strong>
                                </label>
                        </th>
                        <th style="width:125px">
                                <label>
                                    <strong>Technical Skills</strong>
                                </label>
                        </th>
                        <th>
                                <label>
                                     <strong>Career Discription</strong>
                                </label>
                        </th>
                        <th style="width:110px">
                                <label>
                                   <strong>Require Test</strong>
                                </label>
                        </th>
                        <th style="width:100px">
                            <label>
                                <strong>Technology</strong>
                            </label>
                        </th>
                        <th style="width:80px">
                                <label>
                                    <strong>Status</strong>
                                </label>
                        </th>
                        <th style="text-left: right; padding-left:10px;width:100px">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="border-color: #eeeeee; background-color: #eeeeee">
                                    <strong>Action </strong><span ></span>
                                </button>
                                <!--
                                <ul id="menu-privacy" class="dropdown-menu" role="menu">
                                    <li><a  href="javascript: void(0);">Insert</a></li>
                                    <li><a  href="javascript: void(0);">Update</a></li>
                                    <li><a  href="javascript: void(0);">Delete</a></li>
                                </ul>
                                -->
                            </div>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    if($oppportunityList !="") {
                        foreach ($oppportunityList as $k=>$info) {
                            $skillName ="";
                            $testName =""
;                            foreach($info['Skills'] as $skID=>$skName){
                                $skillName = $skillName.'<span><u>'. $skName['SkillName']. '</u></span>'."  ";
                            }

                            foreach($info['Tests'] as $t=>$tName){
                                $testName = $testName .'<span><u>'. $tName['TestName']. '</u></span>'."  ";
                            }
                            if($info['status']== 1){
                                $active = "Active";
                                $color = '#7aac34';
                            } else {
                                $active = "Close";
                                $color = '#ccc';
                            }
                                ?>
                            <tr role="row" class="odd">
                                <td>
                                    <input type="checkbox">&nbsp;<?=$info['posteddate']?><span style="float:right; padding-top:3px; color:#cccccc" class="glyphicon glyphicon-eye-open" ></span>
                                </td>
                                <td><?=$info['title']?></td>
                                <td><?=$skillName?></td>
                                <td><?=$info['careerdescription']?></td>
                                <td ><?=$testName?></td>
                                <td ><?=$info['industry']?>
                                <td style="color: <?=$color?>; font-weight: bold"><?=$active?>

                                </td>
                                <td align="left" style="cursor: pointer"><input class="oppID" type="hidden" value='<?=$info['OpportunityID']?>'">
                                    <a href="careeredit?opportunityID=<?=$info['OpportunityID']?>">
                                    <span class="glyphicon glyphicon-credit-card edit-career-btn" style="color:#7aac34; text-indent: 15px"></span>
                                    </a>
                                    <span class="glyphicon glyphicon-star" style="padding-left:15px;color:#c77405"></span>
                                    <img class="delete-career-btn" onclick="javascript:objCareer.deleteCareer(<?=$info['OpportunityID']?>)" src="<?=URL_THEMES?>images/ico_del.png?>" style="height:15px; width:15px; margin-top:-5px">
                                </td>
                            </tr>
                     <?php   }
                    }

                    ?>


                    </tbody>
                </table>


            </div>
            <!--career list end-->

     </div>
</div>


