                   <div class="col-md-12" >
                        <?php
                        $result = $this->result;
                        if($result!="") {
                            $count =0;
                            foreach($result as $k=>$candidateInfo) {
                                $count ++;
                            if($candidateInfo['image']==""){
                               $image= URL_MEDIA_PHOTO.'avatar_none.jpg';
                            } else{
                                $image = URL_MEDIA_PHOTO.$candidateInfo['image'];
                            }

                                $distance ="";
                                if($candidateInfo['tralveldistanceinmiles'] >1){
                                    $distance = $candidateInfo['tralveldistanceinmiles'] . "miles";
                                } else if($candidateInfo['tralveldistanceinmiles']==1){
                                    $distance = $candidateInfo['tralveldistanceinmiles'] . "mile";
                                } else{
                                    $distance ="";
                                }
                            ?>
                            <div class="col-md-12 borderbottom_Gray" style="padding-right: 0px">
                                <?php
                                if($count >1){
                                    echo '<div class="col-md-12" style="height:10px!important"></div>';
                                }
                                ?>
                                <div class="col-md-12" style="padding-left: 0px">
                                    <div class="col-md-1" style="padding-left: 6px"> <img src="<?=$image?>" style="height:60px;width:50px"></div>
                                    <div class="col-md-11" style="">
                                        <div class="col-md-12" style="color: #1a5187"><strong><?=$candidateInfo['firstname']?> &nbsp; <?=$candidateInfo['lastname']?></strong></div>
                                        <div class="col-md-12"><strong>Expected Salary :  &nbsp;
                                                <?php
                                                if($candidateInfo['minimumsalary']!="" && $candidateInfo['maximumsalary'] !=""){
                                                    echo $candidateInfo['minimumsalary']."K"; echo "-"; echo $candidateInfo['maximumsalary']."K";
                                                } else if($candidateInfo['minimumsalary']!=""){
                                                    echo $candidateInfo['minimumsalary']."K";
                                                } else if($candidateInfo['maximumsalary'] !=""){
                                                    echo $candidateInfo['maximumsalary']."K";
                                                }
                                                ?>

                                                </strong></div>
                                    </div>
                                </div>

                                <div class="col-md-12 text-justify" style="padding-left:0">
                                    <div style="height:10px!important;"></div>
                                    <div class="collapse-group">
                                        <?php
                                        $words = explode(" ",$candidateInfo['overview']);
                                        $str= implode(" ",array_splice($words,0,57))."...";
                                        ?>
                                        <p class="collapse"><?=$candidateInfo['overview']?></p>
                                        <p class="collapse in"><?=$str?></p>
                                        <small><span style="color: #1a5187; cursor: pointer" class="glyphicon glyphicon-play readmore"></span></small><span style="color: #1a5187; font-weight: bold">Read more</span>
                                    </div>
                                </div>

                                <div class="col-md-12" style="padding-left:0">
                                    <div style="height:10px!important;"></div>
                                    <span><strong>Skills:</strong>
                                        <?php
                                        $skillname ="";
                                        $i =1;
                                            foreach ($candidateInfo['skillName']as $kk => $skname){
                                                if($i==1){
                                                    $skillname = $skname;
                                                } else{
                                                    $skillname = $skillname. ', ' . $skname;
                                                }
                                                $i++;
                                            }
                                        ?>
                                    <?=$skillname?>.</span>
                                </div>
                                <div class="col-md-12" style="padding-left:0">
                                    <div style="height:10px!important;"></div>
                                    <span><img src="<?=URL_THEMES?>images/USA_flag.jpg"> <strong>United States</strong></span>
                                    <?php
                                    if($candidateInfo['Address1'] !=""){ ?>
                                        <?=$candidateInfo['Address1']?>;
                                    <?php }
                                    ?>
                                    |&nbsp<strong>Distance:</strong> <?=$distance?></span>
                                </div>
                                <div class="col-md-12 text-right" style="padding-right: 0px">
                                    <button style="margin-top:15px;" class="btn btn-primary" type="button"><strong>Contact</strong></button>
                                </div>
                                <div class="col-md-12" style="margin-left:-30px">
                                    <div style="height:10px!important;"></div>
                                </div>
                            </div>

                            <?php
                            }
                        }
                        ?>

                    </div>





