<script src="<?=URL_THEMES.'js/mobile.career.js';?>"></script>
<style>
    a {
        color: #fff;
        text-decoration: none;
    }
    .nav-tabs {
        border-bottom: 1px solid #ddd;
    }

    .nav-tabs>li.active>a, .nav-tabs>li.active>a:hover, .nav-tabs>li.active>a:focus {
        color: #428bca;
        background-color: #fff;
       /*  border: 1px solid #ddd;*/
        border-bottom-color: transparent;
    }
    .nav-tabs>li>a {
        margin-right: 2px;
        line-height: 1.428571429;
        border: 1px solid transparent;
        border-radius: 4px 4px 0 0;
    }
    .table-striped > tbody > tr:nth-child(2n+1) > td, .table-striped > tbody > tr:nth-child(2n+1) > th {
        background-color:#f7ecb5;
    }
    .table-stripedgray > tbody > tr:nth-child(2n) > td, .table-striped > tbody > tr:nth-child(2n) > th {
        background-color:#eeeeee;
    }

    ol.breadcrumb a{color: #777;}
    ol.breadcrumb .active{color: #fff; background-color: #2a6496;}
    .needHelp {background-color:#edde34 ; min-height: 100px!important; height: auto; width:300px; border-left: 1px solid #cccccc; border-right: 1px solid #cccccc;
    border-bottom: 1px solid #cccccc; float:right; }
    .alignright {text-align: right; padding-right: 50px}
</style>
<div class="container">
    <div style="height:80px; color: #428bca">
        <div class="panel-body">
            <div><h3 style="margin-top: 10px">Post Career</h3></div>
        </div>
    </div>
    <div style="background-color: #2a6496">
        <ul class="nav nav-tabs" id="myTab" style="padding-top:10px" valign="bottom">
            <li class="active" ><a class="calcareercr" href="javascript: void(0);"><strong>New Career</strong></a></li>
            <li ><a id="careerlist" href="javascript: void(0);"><strong>Career List</strong></a></li>
        </ul>
    </div>
    <div class="tab-content">
        <!--create career-->
            <div class="tab-pane active">
                <div class="panel panel-default">
                    <div class="panel-body">
                    <ol class="breadcrumb">
                        <li><a class="calcareercr"  href="javascript: void(0);" ><strong>1 Create Career</strong></a></li>
                        <li><a href="#"><strong>2 Create Private</strong></a></li>
                        <li><a class="previewpost active" href="javascript: void(0);"><strong>3 Preview</strong></a></li>

                    </ol>
                        <table  cellspacing="0" width="100%">
                            <col width="250px">
                            <col width="*">
                            <tr>
                                <td class="alignright"><strong>Career Name*</strong></td>
                                <td>test</td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Company Name*</strong></td>
                                <td>test</td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Career Description*</strong></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Industry*</strong></td>
                                <td ></td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Career Type</strong> </td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Career Location</strong></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Minimun Education*</strong></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Degree Title*</strong> </td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Required Skills*</strong></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Required Experience*</strong> </td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Salary Range*</strong> </td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="alignright"><strong>Required Test</strong> </td>
                                <td></td>
                            </tr>
                        </table>
                    </div>
                    <!--END RIGHT-->
                    <div style="margin-left: 60px">
                        <button id="" style="width:100px" type="button" class="btn btn-primary" data-loading-text="Loading..."><strong>Post Career</strong></button>
                        <button id="" style="width:115px; margin-left: 20px; color: white;" type="button" class="btn " data-loading-text="Loading..."><strong>Edit Post</strong></button>
                        <button id="" style="width:100px;margin-left: 20px;color: white;" type="button" class="btn " data-loading-text="Loading..."><strong>Post Career Later</strong></button>
                        <button id="" style="width:100px;margin-left: 20px;color: white;" type="button" class="btn " data-loading-text="Loading..."><strong>Save Career</strong></button>
                    </div>

                </div>
            </div>
            <!--end create career-->


     </div>
</div>


