<style>

    .panel-heading .accordion-toggle:after {
        /* symbol for "opening" panels */
        font-family: 'Glyphicons Halflings';  /* essential for enabling glyphicon */
        content: "\e114";    /* adjust as needed, taken from bootstrap.css */
        float: right;        /* adjust as needed */
        color: #fff;         /* adjust as needed */
    }
    .panel-heading .accordion-toggle.collapsed:after {
        /* symbol for "collapsed" panels */
        content: "\e080";    /* adjust as needed, taken from bootstrap.css */
    }
    #accordion .col-md-3,.col-md-6{margin:0;padding:0}
    #accordion .item-container{
        -webkit-border-radius: 0;
        -moz-border-radius: 0;
        border-radius: 0;
        margin:0; border-top:0;
    }
    ul.test-list-item{
        margin:0;padding:0;list-style: none;
    }
    ul.test-list-item .item-header{}
    ul.test-list-item .item-list{padding: 5px;margin:0;  border-bottom: 1px solid #ccc;}


</style>
<div class="container" >
    <div class="page-header">
        <h3><span class="text-left" style="color: #2a6496">Watchlist</span>
        <span class="pull-right">
            <button class="btn btn-sm btn-success" type="button"><strong>Create New Test</strong></button>
        </span>
        </h3>
    </div>

    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-color: #2a6496;color: #fff">
                <h4 class="panel-title" >
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                        Questions Sheet - Total 3
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body" style="padding-top:0;padding-bottom: 0">
                    <div class="row">
                        <div class="col-md-3">
                            <ul class="test-list-item">
                                <li  class="item-list"><label><input type="checkbox"/> Question 1</label></li>
                                <li class="item-list"><label><input type="checkbox"/> Question 1</label></li>
                                <li class="item-list"><label><input type="checkbox"/> Question 1</label></li>
                                <li class="item-list"><label><input type="checkbox"/> Question 1</label></li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <ul class="test-list-item">
                                <div class="panel panel-default  item-container">
                                    <div class="panel-body item-container">
                                        <form id="" role="form">
                                            <div class="form-group">
                                                <label><a>Question</a></label>
                                                <input name="" type="text" class="form-control" id="" placeholder="Question">
                                            </div>
                                            <div class="form-group">
                                                <label for="credential"><a>Answer Option</a></label>
                                                <textarea class="form-control" placeholder="Answer Option"></textarea>
                                            </div>
                                            <div class="col-xs-12">

                                            <p class="pull-right"><a class="lbl-log" href="#">Add More Option</a></p>
                                                </div>
                                            <button data-loading-text="Loading..." id="btn-login" class="btn btn-success" type="button">Save Question</button>
                                        </form>
                                    </div>
                                </div>

                            </ul>
                        </div>
                        <div class="col-md-3">
                            <ul class="test-list-item">
                                <li  class="item-list"><label><input type="checkbox"/> Question 1</label></li>
                                <li class="item-list"><label><input type="checkbox"/> Question 1</label></li>
                                <li class="item-list"><label><input type="checkbox"/> Question 1</label></li>
                                <li class="item-list"><label><input type="checkbox"/> Question 1</label></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" style="background-color: #2a6496;color: #fff">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                        Collapsible Group Item #2
                    </a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" style="background-color: #2a6496;color: #fff">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                        Collapsible Group Item #3
                    </a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse">
                <div class="panel-body">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div>
            </div>
        </div>
    </div>

</div>
<script>

</script>