
<style>

body {
    background: none repeat scroll 0 0 #ededed;
    
}
.btn-primary1 {
    background-color: #333;
    border-color: #fff;
    color: #fff;
}
.btn-primary {
    background-color: #005595;
    border-color: #fff;
    color: #fff;
    font-family:"Open Sans" ;
}
.link{
    
    margin-top: 30px;
    margin-bottom: 20px;
    background-color: #fff;
    border: 1px ;
    border-color: #fff;
    border-radius: 5px;
    max-width: 290px;
    /*width: 310px;;*/
    padding-bottom: 10px;
    font-size: 11px;
    line-height: 200%;
    /*font-family:"Open Sans" ;*/
}
.text{
    font-family:"Open Sans" ;
}
.image {
    background: url('<?=URL_THEMES?>images/bg2.jpg') no-repeat ;

    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
    -o-background-size: cover;
    padding-left:3%;
    max-width: 100%;
    
    
    
   
}
.img{
    width: 20px;
   /* height: 15px;*/
    padding-right: 5px;;
}
.col{
    width: 50%;
    font-size: 12px;
}
.col1{
    width: 200px;;
    float: right;
}
.container{
    max-width: 90%;
}.img1{
    /* background: url('<?=URL_THEMES?>images/Img_A.jpg') no-repeat ;*/

    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
    -o-background-size: cover;

    max-width: 100%;
   /* max-width: 875px ;*/
}
#form-login .message{color: #b81900;}
</style>
<!--<div style="background-color: #d1dce2; padding-left:47px;" >style=" padding-left:47px;"-->
<div  class="image" style="background-color: #d1dce2;" >
    <div class="container" >
       <div class="col-xs-4"  style="padding:0;padding-top:40px;">
            <span class="" style="font-size:14px;">The most advanced technology for your</span>
            <br><span class="" style="font-weight:bold;font-size:30px;color:#125196;">Recruitment Efforts</span>
            <div style="padding-top:30px;">
                    <span ><img src="<?=URL_THEMES?>images/btn_company.png" ></span>
                    <span style="padding-left:5px;"><img src="<?=URL_THEMES?>images/btn_candidate.png" ></span>
            </div>
            <div class="link" style="padding-top:10px;padding-left:10px;">
                    <span ><img class="img" src="<?=URL_THEMES?>images/ico_arrowR.png" >Deep screening technology</span><br>
                    <span ><img class="img" src="<?=URL_THEMES?>images/ico_arrowR.png" >Machine Learning Techonology</span><br>
                    <span><img class="img" src="<?=URL_THEMES?>images/ico_arrowR.png" >Collaboratlve, full-suite of recruiting tools </span><br>
                    <span><img class="img" src="<?=URL_THEMES?>images/ico_arrowR.png" >All features are enhanced with Machine Learning </span><br>
            </div>
        </div>
       

    </div>
</div>    
<div class="header" style="background-color: #343434;padding: 10px 0px; color: #fff;">
        <div class="container">
             <div class="col-xs-8" style="padding:0">
                <span style="font-size:14px;">This is the resume of the future! With Pocket Recruiter, </span><br/>
                <span style="font-weight:bold;font-size:20px;">Proven methodology, profound impact,<br> and sustainable results.</span>
            </div>
            <div class="col-xs-4" style="padding-top:20px;padding-left:150px;">
                <span style="padding-left:13px;"><img src="<?=URL_THEMES?>images/btn_WatchDemo.png"  class="img1"></span>
                
            </div>
        </div>
    </div>
<div style="background-color: #ededed" style="padding-left:50px;">
    <div class="container" style="padding-top:20px;" >
       
        <div class="col-xs-7" style="padding:0;padding-left:3px;font-size:11px">
            <h3><span style="color:#005595;font-weight:bold;font-size:25px">About Pocket Recruiter</span></h3><br>
            <p>Intege libero mi, dictum pretium dignissim eget, priteum quis justo. Cras non dolor a neque accumsam vehicula. Sed iaculis pritium eros, et consectetur orci placerat et. Vivamus nisl libero, rutrum id resus a, facilisis lacinia risus.</p>
            <p>pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpic egestas. Donec at dapibus leo, sit amet rhoncus ante. Praesent non augue dolor. Nullam nec justo ut dui tristique sollicitu-din. Donec ut mauris libero. Vestibulum sapien nulla, vehicula ut nulla sit amet, ultricies convallis nullar. </p>
            
            
        </div>
        <div class="col-xs-5">
            <span style="padding-left:13px"><img class="img1" src="<?=URL_THEMES?>images/screen.jpg" ></span>
        </div>

    </div>
    <div class="container" style="padding-top:40px;" >
       
        <div class="col-xs-12" style="padding:0;padding-left:3px;font-size:12px">
           
             <img class="img1" src="<?=URL_THEMES?>images/Img_A.jpg" >
        </div>
       

    </div>
    <div class="container" style="padding-top:40px;" >
       
        <div class="col-xs-6" style="padding:0;padding-left:3px">
           
             <span style="font-weight:bold;font-size:18px;">Advanced Crawler to find passive candidate</span><br><br>
             <p style="font-size:11px">Intege libero mi, dictum pretium dignissim eget, priteum quis justo. Cras non dolor a neque accumsam vehicula. Sed iaculis pritium eros, et consectetur orci placerat et. Vivamus nisl libero, rutrum id resus a, facilisis lacinia risus.pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpic egestas. Donec at dapibus leo, sit amet rhoncus ante. Praesent non augue dolor. </p></span>
        </div>
        <div class="col-xs-6">
            
             <span style="font-weight:bold;font-size:18px;">Highly screened, verifile candidates</span><br><br>
             <p style="font-size:11px">Intege libero mi, dictum pretium dignissim eget, priteum quis justo. Cras non dolor a neque accumsam vehicula. Sed iaculis pritium eros, et consectetur orci placerat et. Vivamus nisl libero, rutrum id resus a, facilisis lacinia risus.pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpic egestas. Donec at dapibus leo, sit amet rhoncus ante. Praesent non augue dolor.</p>
        </div>

    </div>
    <div class="container" style="padding-top:40px;" >
    </div>
    
</div>

<script>
    //Init main pocket
    var pkMain = new pocketMain();
    $(document).ready(function(){
        //Login pocket
        $('#btn-login').unbind('click').bind('click',pkMain.logIn);
    })
</script>