<script language="javascript">
    var valRules=new Array();
    valRules[0]='username:Username|required';
    valRules[1]='password:Password|required';
</script>
<center>
    <div class="login_box">
        <form name="frmForgotPassword" id="frmForgotPassword" action="" method="post">
            <table width="100%" border="0" align="center" cellpadding="4" cellspacing="0">
                <tr>
                    <td colspan="3">
                        <div class="validate-error"></div>
                    </td>
                </tr>
                <tr>
                    <td width="36%">
                        <div align="right">Username</div>
                    </td>
                    <td width="1%" align="center" style="vertical-align:middle;">
                        <strong>:</strong>
                    </td>
                    <td width="63%">
                        <input name="username" type="text" id="username" value="" size="20" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <div align="right">Email</div>
                    </td>
                    <td align="center" style="vertical-align:middle;">
                        <strong>:</strong>
                    </td>
                    <td>
                        <input name="email" type="text" id="email" size="20" />
                    </td>
                </tr>

                <tr>
                    <td colspan="2">&nbsp;</td>
                    <td>
                        <input type="button" class="btnType1 btnSubmit" value="Login" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                    <td>
                        <a href="<?= URL_BASE . "login/index" ?>">Click here to login</a>
                    </td>
                </tr>  
            </table>
        </form>
    </div>
</center>
