<div class="header" style="background-color: #333;padding: 10px 0; color: #fff;">
    <div class="container">
        <small>This is the resume of the future! With Pocket Recruiter, </small><br/>
        You'll not only get the hiring manager's attention-you'll keep it
    </div>
</div>
<div class="container" >
<div class="page-header" style="margin:0;">
    <h1>
        <span class="text-left" style="color: #2a6496">Log In</span>
        <span class="text-right pull-right" style="font-size: 14px;position: relative;top: 20px">Already have a Pocket Recruiter account? <span class="lbl-log">Sign in</span> <span class="lbl-log">Register</span></span>

    </h1>
</div>
<div class="col-md-8"  style="padding:0">
    <div class="col-md-6" style="margin:0;padding:0">
        <form id="form-login" role="form">
            <div class="form-group">
                <label for="email">Email address</label>
                <input name="email" type="email" class="form-control" id="email" placeholder="Enter email">
                <span class="username_message"></span>
            </div>
            <div class="form-group">
                <label for="credential">Password</label>
                <input name="password"  type="password" class="form-control" id="credential" placeholder="Password">
                <span class="password_message"></span>
                <p class="help-block" id=""><a href="reset">Forgot Password?</a></p>
            </div>
            <div class="form-group">
                <span><input name="remember" type="checkbox" id="terms"> Remember Me</span>
                <span class="pull-right">
                    <a href="#">Forget Password</a>
                </span>
            </div>
            <button data-loading-text="Loading..." id="btn-login" class="btn btn-primary" type="button">Sign In</button>
        </form>
    </div>
    <div class="col-md-6">
    </div>

</div>
<div class="col-md-4" style="padding:0;border-left: 1px solid #ddd; height: 400px;">
    <div style="height: 50px; ">
        <p style="float:left;width: 20%;color: #fff;background-color: #4cae4c;padding: 15px 0; text-align: center"><i class="glyphicon glyphicon-lock"></i></p>
        <p style="float:left;width: 80%;color: #fff;background-color: #333;padding: 5px 0; text-align: center">
            We value your privacy<br/> <small>Privacy Policy</small>
        </p>
    </div>
    <div class="col-lg-12">
       <h3><span class="text-left" style="color: #2a6496;padding-right: 20px;"><i class="glyphicon glyphicon-ok"></i></span><span class="text-center" >Pocket Recruiter</span></h3>
        <p><smal>
            At a bare minimum, the front controller needs one or more paths to directories containing action controllers in order to do its work. A variety of methods may also be invoked to further tailor the front controller environment and that of its helper classes.</smal>
        </p>
        <p><span class="lbl-log">Register</span></p>
    </div>
</div>
</div>
<script>
    //Init main pocket
    var pkMain = new pocketMain();
    $(document).ready(function(){
        //Login pocket
        $('#btn-login').unbind('click').bind('click',pkMain.logIn);
    })
</script>