<!DOCTYPE html>
<html>
    <head>
        
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <script type="text/javascript" src="<?= URL_THEMES . "js/jquery/jquery-1.7.2.min.js" ?>"></script>
        <script type="text/javascript" src="<?= URL_THEMES . "js/jquery/jquery-ui-1.8.21.custom.min.js" ?>"></script>
        <script type="text/javascript" src="<?= URL_THEMES . "js/fun.js" ?>"></script>
        <script type="text/javascript" src="<?= URL_THEMES . "js/menu.js" ?>"></script>
        <script type="text/javascript" src="<?= URL_THEMES . "js/home.js" ?>"></script>
        <script type="text/javascript" src="<?= URL_THEMES . "js/PrintArea.js" ?>"></script>

       <!-- <link rel="stylesheet" type="text/css" href="<?= URL_THEMES . "css/ui-lightness/jquery-ui-1.8.21.custom.css" ?>"/>
        <link rel="stylesheet" type="text/css" href="<?= URL_THEMES . "css/main.css" ?>"/>
        <link rel="stylesheet" type="text/css" href="<?= URL_THEMES . "css/porlet.css" ?>"/>
        <link rel="stylesheet" type="text/css" href="<?= URL_THEMES . "css/verticalmenu.css" ?>"/>
        <link rel="stylesheet" type="text/css" href="<?= URL_THEMES . "css/transcript.css" ?>"/>-->
        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>PocketRecruiter</title>

        <!-- Bootstrap Core CSS -->
        
        <link rel="stylesheet" type="text/css" href="<?= URL_THEMES . "css/bootstrap.min.css" ?>"/>

        <!-- Custom CSS -->
        
        <link rel="stylesheet" type="text/css" href="<?= URL_THEMES . "css/full.css" ?>"/>
        

       
    </head>

    <body>
    
    <!--new-->
                
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                    <a href="#"><img height="52px" src="<?= URL_THEMES . 'img/logo/logo.png' ?>" alt="" tilte=""/></a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li> <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Dashboard">Dashboard <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Start Profile</a></li>
                            <li><a href="#">Recent Notifications</a></li>
                            <li><a href="#">Technical Tests</a></li>
                        </ul>
                    </li>
                    <li> <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Dashboard">Post Career <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Recently posted career list</a></li>
                            <li><a href="#">New Career</a></li>
                        </ul>
                    </li>
                    <li><a href="javascript: void(0)">Career Match</a></li>
                    <li><a href="javascript: void(0)">Activities</a></li>
                    <li><a id="cmd-logout" href="javascript: void(0)">Logout</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div id="contentPage" class="contentPage">
        <?php echo $this->layout()->content; ?>
    </div>
    <div class="footer">
    
</div>
    <!--new-->

    </body>
</html>
