<?php
$helper = $this->layout()->_helper;
?>
<!DOCTYPE html>
<html class="full" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>PocketRecruiter</title>
    <link href="<?=URL_THEMES.'css/bootstrap.min.css';?>" rel="stylesheet">
    <link href="<?=URL_THEMES.'css/datepicker.css';?>" rel="stylesheet">
    <link href="<?=URL_THEMES.'css/main.css';?>" rel="stylesheet">
    <script src="<?=URL_THEMES.'js/jquery-1.11.0.js';?>"></script>
    <script src="<?=URL_THEMES.'js/bootstrap.min.js';?>"></script>
    <script src="<?=URL_THEMES.'js/bootstrap-datepicker.js';?>"></script>
    <script src="<?=URL_THEMES.'js/pocket.main.js';?>"></script>

</head>

<body>
<div class="modal fade" tabindex="-1" role="dialog" id="modal-dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title" id="myModalLabel"></h2>
            </div>
            <div class="modal-body login-modal">
                <div id="modal-content"></div>
            </div>
        </div>
    </div>
</div>

<!-- Navigation -->
<?php
$loginClient = $this->layout()->loginclient;
?>
<nav class="navbar  navbar-default navbar-fixed-top" role="navigation">
    <?php if(empty($loginClient)){?>
        <div class="nav-ribbon navbar-header">
            <div class="nav-ribbon-left pull-right">
                <?php $loginClient = $this->layout()->loginclient; if(!empty($loginClient)){ ?>
                    <strong><?=$loginClient['emailaddress'];?></strong> / <a href="javascript: void(0)" id="btn-logout" data-url="<?=$this->layout()->logout;?>">Logout</a>
                <?php }else{ ?>
                    <a href="<?=URL_BASE;?>register">SignIn or Join</a>
                <?php } ?>
            </div>
        </div>
    <?php } ?>

    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="#"><img height="52px" src="<?=URL_THEMES.'images/logo.png'?>" alt="" tilte=""/></a>

        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <?php if(empty($loginClient)){ ?>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><strong>Match Career</strong></a></li>
                <li><a href="#"><strong>Features</strong></a></li>
                <li><a href="#"><strong>Plans</strong></a></li>
                <li><a href="#"><strong>Success Stones</strong></a></li>
                <li><a href="#"><strong>Resources</strong></a></li>
                <li><a href="#"><strong>Contact Us</strong></a></li>
            </ul>
            <?php }else{ ?>
                <ul class="nav nav-pills navbar-right small">

                    <li class="dropdown">
                        <span class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <strong><?=$loginClient['emailaddress']?></strong><span class="caret"></span>
                        </span>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="<?= URL_BASE . 'client/profile' ?>"><i class="glyphicon glyphicon-user"></i> Edit Profile</a></li>
                            <li class="divider"></li>
                            <li><a href="javascript: void(0)" id="btn-logout" data-url="<?=$this->layout()->logout;?>"><i class="glyphicon glyphicon-log-out"></i> Logout</a></li>
                        </ul>
                    </li>
                    <li><a href="<?=$helper->url('list','notifications');?>">Notifications</a></li>
                    <li><a href="<?=$helper->url('list','companyprofile');?>">Settings</a></li>
                    <li><a href="#">Helps</a></li>
                </ul>
            <?php } ?>

        </div>

    </div>

    <?php if(!empty($loginClient)){ ?>
        <?php if($loginClient['usertype']==1){ ?>
            <div class="nav-ribbon-bottom">
                <ul class="nav-parent">
                    <li class="dropdown">
                        <a class="link" class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Dashboard <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu" style="margin-top: -1px">
                            <li><a href="<?=$helper->url('index','test');?>">Manager Test</a></li>
                        </ul>
                    </li>
                    <li><a class="link" href="#">Post Career</a></li>
                    <li><a class="link" href="#">Match Candidate</a></li>
                    <li><a class="link" href="#">Activities</a></li>
                    <li><a class="link" href="#">Notifications</a></li>
                    <li><a class="link" href="#">Watch List</a></li>
                </ul>
            </div>
        <?php }elseif($loginClient['usertype']==2){ ?>
            <div class="nav-ribbon-bottom">
                <ul class="nav-parent">
                    <li><a class="link" href="#">Profile Builder</a></li>
                    <li><a class="link" href="#">My Profile</a></li>
                    <li><a class="link" href="#">Activities</a></li>
                    <li><a class="link" href="#">Match Opportunities</a></li>
                </ul>
            </div>
        <?php } ?>

    <?php } ?>
    <!-- /.container -->
</nav>
<!--Container-->
<?php echo $this->layout()->content; ?>
<!--End Container-->

<div id="footer">
    <div class="container">
        <div class="col-md-2">
            <h5><strong style="color: #2a6496">Product</strong></h5>
            <ul class="fa-list">
                <li><a href="#">Features</a></li>
                <li><a href="#">Plans</a></li>
                <li><a href="#">Success Stories</a></li>
                <li><a href="#">FAQs</a></li>
            </ul>
        </div>
        <div class="col-md-2">
            <h5><strong style="color: #2a6496">Resources</strong></h5>
            <ul class="fa-list">
                <li><a href="#">Blog</a></li>
                <li><a href="#">Resources</a></li>
            </ul>
        </div>
        <div class="col-md-2">
            <h5><strong style="color: #2a6496">Company</strong></h5>
            <ul class="fa-list">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Press Releases</a></li>
                <li><a href="#">News</a></li>
                <li><a href="#">Partners</a></li>
                <li><a href="#">Team</a></li>
            </ul>
        </div>
        <div class="col-md-2">
            <h5><strong style="color: #2a6496">Follow</strong></h5>
            <ul class="fa-list">
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">LinkedIn</a></li>
                <li><a href="#">Google+</a></li>
            </ul>
        </div>
        <div class="col-md-2">
            <h5><strong style="color: #2a6496">Contact Us</strong></h5>
            <ul class="fa-list">
                <li><a href="#">Email Sale</a></li>
                <li><a href="#">(000) 123-4567</a></li>
                <li><a href="#">Email Support</a></li>
                <li><a href="#">(000) 123-4567</a></li>
                <li><a href="#">6am-6p Pt daily</a></li>
            </ul>
        </div>
    </div>
</div>
<!--Footer-->
<!--End Container-->
</body>

</html>
