<!DOCTYPE html>
<html>
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>PocketRecruiter</title>

        <!-- Bootstrap Core CSS -->
        <link href="<?=URL_THEMES_MOBILE.'css/bootstrap.min.css';?>" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="<?=URL_THEMES_MOBILE.'css/full.css';?>" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <!--<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <!-- jQuery Version 1.11.0 -->
        <script src="<?=URL_THEMES_MOBILE.'js/jquery-1.11.0.js';?>"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="<?=URL_THEMES_MOBILE.'js/bootstrap.min.js';?>"></script>
        <script src="<?=URL_THEMES_MOBILE.'js/mobile.profile.js';?>"></script>

    </head>

    <body>
    
    <!--new-->
                
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="<?= URL_THEMES_MOBILE . 'images/logo.png' ?>" alt="" tilte=""/>
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li> <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Dashboard">Dashboard <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Start Profile</a></li>
                            <li><a href="#">Recent Notifications</a></li>
                            <li><a href="#">Technical Tests</a></li>
                        </ul>
                    </li>
                    <li> <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Dashboard">Post Career <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Recently posted career list</a></li>
                            <li><a href="#">New Career</a></li>
                        </ul>
                    </li>
                    <li><a href="javascript: void(0)">Career Match</a></li>
                    <li><a href="javascript: void(0)">Activities</a></li>
                    <li><a id="cmd-logout" href="javascript: void(0)">Logout</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div id="contentPage" class="contentPage">
        <?php echo $this->layout()->content; ?>
    </div>
    <div class="footer">
    
</div>
    <!--new-->

    </body>
</html>
