<!DOCTYPE html>
<html class="full" lang="en">
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PocketRecruiter</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?=URL_THEMES_MOBILE.'css/bootstrap.min.css';?>" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?=URL_THEMES_MOBILE.'css/full.css';?>" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <!--<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<style>
    .modal-dialog-center {
        margin-top: 10%;
        transform: translate(0, 50%) !important;
        -ms-transform: translate(0, 50%) !important; /* IE 9 */
        -webkit-transform: translate(0, 50%) !important; /* Safari and Chrome */
    }
    #form-login .message{padding-top: 3px; font-style: italic;color: #b81900;font-size:12px;}
</style>

<div class="modal fade" tabindex="-1" role="dialog" id="login-modal" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content modal-dialog-center">
            <div class="modal-header login_modal_header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title" id="myModalLabel">Sign In</h2>
            </div>
            <div class="modal-body login-modal">
                <form id="form-login" name="form-login">
                <div id="login-message">

                </div>
                <div>
                    <div class='modal-body-left'>
                        <div class="form-group">
                            <input type="text" name="username" id="username" placeholder="User Name" class="form-control login-field">
                            <span class="message" id="username_message"></span>
                        </div>
                        <div class="form-group">
                            <input type="password" name="password" id="password" placeholder="Password" class="form-control login-field">
                            <span class="message" id="password_message"></span>
                        </div>
                        <p><a href="#" class="login-link text-center">Forgot your password?</a></p>
                        <button id="cmd-login" type="button" class="btn btn-primary modal-login-btn" data-loading-text="Loading...">Sign In</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="#"><img height="52px" src="<?=URL_THEMES_MOBILE.'images/logo.png'?>" alt="" tilte=""/></a>

        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<div class="row">
    <p style="display:block;line-height: 70px; width:110%; text-align:center; top: 65%; position:absolute;">
        <a id="show-login" href="#" data-toggle="modal" data-target="#login-modal"><img src="<?=URL_THEMES_MOBILE.'images/btn_login.png'?>" alt="" title="" style="height: 60px"/></a>
    </p>
</div>
<!-- Put your page content here! -->

<!-- jQuery Version 1.11.0 -->
<script src="<?=URL_THEMES_MOBILE.'js/jquery-1.11.0.js';?>"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?=URL_THEMES_MOBILE.'js/bootstrap.min.js';?>"></script>
<script src="<?=URL_THEMES_MOBILE.'js/mobile.login.js';?>"></script>

</body>

</html>
