<form name="frmprofile" id="frmprofile" method="post" action="<?= URL_BASE . 'client/filter-edit?ajax=1' ?>">
 <div class="panel-body" style="">
   <h1><span style="color: #357ebd">Profile</span></h1>
   <div align="center" style="">
    <table width="100%" cellspacing="10px" cellpadding="10px">
    <col width="30%">
    <col width="*">
        <tr>
                <td>
                    Client ID
                </td>
                <td>
                    12345
                </td>
        </tr>
        <tr>
                <td>
                    User Name
                </td>
                <td>
                    <input type="text"  name=""  value="pr" />
                </td>
        </tr>
        <tr>
                <td>
                    Password
                </td>
                <td>
                    <input type="password"  name=""  value="Test1234" />
                </td>
        </tr>
        <tr>
                <td>
                    Company Name
                </td>
                <td>
                    <input type="text"  name=""  value="Test1234" />
                </td>
        </tr>
        <tr>
                <td>
                    Company ID
                </td>
                <td>
                    <input type="text"  name=""  value="PocketRecruiter" />
                </td>
        </tr>
        <tr>
                <td>
                    Company ID
                </td>
                <td>
                    <input type="text"  name=""  value="12345" />
                </td>
        </tr>
        <tr>
                <td>
                    Contact Name
                </td>
                <td>
                    <input type="text"  name=""  value="test" />
                </td>
        </tr>
        <tr>
                <td>
                    Contact Phone1
                </td>
                <td>
                    <input type="text"  name=""  value="0123456789" />
                </td>
        </tr>
        <tr>
                <td>
                    Contact Phone2
                </td>
                <td>
                    <input type="text"  name=""  value="0123456789" />
                </td>
        </tr>
        <tr>
                <td>
                    Email1
                </td>
                <td>
                    <input type="text"  name=""  value="nhunguyet.ntn@gmail.com" />
                </td>
        </tr>
         <tr>
                <td>
                    Email2
                </td>
                <td>
                    <input type="text"  name=""  value="nhunguyet.ntn@gmail.com" />
                </td>
        </tr>
         <tr>
                <td>
                    Business Address
                </td>
                <td>
                    <input type="text"  name=""  value="HCM city" />
                </td>
        </tr>
         <tr>
                <td>
                    Business City
                </td>
                <td>
                    <input type="text"  name=""  value="HCM city" />
                </td>
        </tr>
        <tr>
                <td>
                    Business State
                </td>
                <td>
                    <input type="text"  name=""  value="bla bla..." />
                </td>
        </tr>
        <tr>
                <td>
                    Business Zip
                </td>
                <td>
                    <input type="text"  name=""  value="86435" />
                </td>
        </tr>
        <tr>
                <td colspan="2">
                    Company Description
                </td>
                
        </tr>
        <tr>
                <td colspan="2">
                    <textarea rows="5" style="width: 47%;" name="CompanyDescription" id="EditRecordCompanyDescription"></textarea>
                </td>
                
        </tr>
         <tr>
                <td>
                    RegDate
                </td>
                <td>
                    <input type="text"  name=""  value="" />
                </td>
        </tr>
         <tr>
                <td>
                    Account Enabled
                </td>
                <td>
                    <input type="text"  name=""  value="" />
                </td>
        </tr>
        <tr>
                <td>
                    Company Logo
                </td>
                <td>
                    <div style="float:left;width:450px; ">
                                                                  
                                <div id="Company_Logo_file">
                                    <input type="file" id="Company_Logo" style="size:20;" name="Company_Logo">
                                 </div>   
                                 </div>
                </td>
        </tr>
        <tr>
                <td>
                    Country
                </td>
                <td>
                    <input type="text"  name=""  value="" />
                </td>
        </tr>
         <tr>
                <td>
                    Created By
                </td>
                <td>
                    <input type="text"  name=""  value="" />
                </td>
        </tr>
         <tr>
                <td>
                    Last Login Date
                </td>
                <td>
                    <input type="text"  name=""  value="" />
                </td>
        </tr>
        <tr><td colspan="2"><br/></td></tr>
        <tr >
            <td style="float:right">
            <div class="">
            
                <button type="button" class="btn btn-success">
                    <strong>Update</strong>
                </button>
            
             </div>
            </td>
        </tr>
    </table>
    </div>
    
 </div>
</form>