<header class="subhead" id="overview">
    <div class="panel panel-primary" style="border:0">
        <div class="panel-heading">
            <h3 class="panel-title">
                <strong>Technical Test</strong>
            </h3>
        </div>
        <div class="panel-body">
            <span class="tag-tech"><a href="#"><strong>Joomla</strong> (22,Jan)</a> <i class="glyphicon glyphicon-remove"></i></span>
            <span class="tag-tech"><a href="#"><strong>Drupal</strong> (16,Fer)</a> <i class="glyphicon glyphicon-remove"></i></span>
            <span class="tag-tech"><a href="#"><strong>Wordpress</strong>(16,Aug)</a> <i class="glyphicon glyphicon-remove"></i></span>
            <span class="tag-tech"><a href="#"><strong>Java</strong></a> <i class="glyphicon glyphicon-remove"></i></span>
            <span class="tag-tech"><a href="#"><strong>ASPX</strong></a> <i class="glyphicon glyphicon-remove"></i></span>
        </div>

    </div>
</header>

<div class="row">
    <div style="padding-left: 15px;position: absolute;width: 100%; top: 90%;">
        <div class="col-xs-6">
            <button  data-toggle="modal" data-target="#login-modal" id="show-login" class="btn btn-primary" type="button">
                <span style="font-size: 1.2em;font-weight: bold">Create New Test</span>
            </button>
        </div>
        <div class="col-xs-6">
            <h4 class="pull-right"> 4 Test </h4>
        </div>
    </div>
</div>


<style>
    .tag-tech{
        float:left; margin: 5px 10px 0 0;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
        border: 1px solid #ddd;padding: 7px;
        background-color: #f2f2f2;
    }
</style>